### ISSUE TITLE
Docs-Articles-Templates extension breaks VSCode http requests

### ISSUE THREAD

**Issue by shana** [Microsoft/vscode-docs-authoring#100]
:wave:

We just stumbled onto a problem over at the VSCode GitHub Pull Requests extension, where our GitHub sign in flow breaks when the Docs-Articles-Templates extension is installed. The relevant issue is https://github.com/Microsoft/vscode-pull-request-github/issues/449

Essentially, it looks like docs-articles-templates is referencing an old version of `vscode-extension-telemetry`, which in turn is pulling in a really old version of `applicationinsights-nodejs`, which has a bug where it throws trying to parse a request (in this case, a web socket connection), completely breaking any extension trying to do http requests.

I'm trying to find a workaround right now, but it would be great if you could update your dependencies to their latest version, which will hopefully fix these issues.

**Comment by meganbradley** [comment]
@adkinn can someone review Jamar's PR?
