### ISSUE TITLE
Failed to install extension dependencies

### ISSUE THREAD

**Issue by paule96** [Microsoft/vscode-docs-authoring#102]
Hi People,

I have a issue with download and install the latest markdocs-server. 

![image](https://user-images.githubusercontent.com/11291885/45938899-85936e00-bfce-11e8-8c6f-e0a01da3f1c1.png)

Do anybody know how to fix this? I think it Maybe the same Problem like [here](https://github.com/Microsoft/vscode/issues/2384)

**Comment by jamarw** [comment]
Hi @paule96 , looping in @qinezh for assistance.  Thanks

**Comment by paule96** [comment]
any updates?

**Comment by qinezh** [comment]
@paule96 Checking

**Comment by paule96** [comment]
Repro steps:
1. Open VS Code
2. Install the Extension [Docs Authoring Pack](https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-authoring-pack)
3. Open a markdown file
4. Look at the output window of vscode in the "tab" "extensions".
5. See the output of this issue

Enviroment:
- Windows 10 Enterprise 1803
- Network tested with HTTP-Proxy and without
- VSCode Version 1.28.0
- Docs Authoring Pack Version 0.1.1

That are all Information I have.

**Comment by qinezh** [comment]
Thanks @paule96, can you please try the latest version(0.3.14) of docs-preview?

**Comment by paule96** [comment]
Yes it works.
So Docs Authoring Pack must update the dependencies.

@jamarw can you help here?

**Comment by qinezh** [comment]
From my understanding, there's no need to update Docs Authoring Pack from my understanding, as vscode will update the dependencies by default.

**Comment by qinezh** [comment]
Closed it and please reopen it if you have further question 😄
