### ISSUE TITLE
Inserting an image doesn't show list of image files

### ISSUE THREAD

**Issue by jmsnavarro** [Microsoft/vscode-docs-authoring#131]
Alt + M > Image > type ToolTip > Press Enter > doesn't show list of image files

**Comment by jamarw** [comment]
Hi @jmsnavarro , do you have a sample repo or content set I can use for troubleshooting?  I haven't been able to repro the issue on my side.  Thanks

**Comment by jmsnavarro** [comment]
Hi @jamarw , I created a new folder and move my files to it and the issue is now gone.
