### ISSUE TITLE
Flag code fence with more than three backticks

### ISSUE THREAD

**Issue by nschonni** [microsoft/vscode-docs-authoring#132]
I've come across this in the docs and it can cause rendering issues. Seems like it might be a straightforward rule like you've done with the Alert rules

**Comment by jamarw** [comment]
Hi @nschonni , thanks for catching this.  Looping in @meganbradley for follow-up.

**Comment by meganbradley** [comment]
Added to backlog for markdownlint extensions. CC @lamebrain @jamarw

**Comment by lamebrain** [comment]
Closing as a stale issue. Please open a new issue if this is still a problem.
