### ISSUE TITLE
Can't navigate to links that begin with tildes

### ISSUE THREAD

**Issue by DennisLee-DennisLee** [microsoft/vscode-docs-authoring#135]
Links that begin from the docset root (i.e., links that begin with a tilde, like `[load tests](~/test/unit-test/load-tests.md)`) currently don't work when you click on them in preview. Could you please fix this issue? Thanks.

[AB#239486](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/239486)

**Comment by nschonni** [comment]
FYI, it isn't recommend to use those links https://docs.microsoft.com/en-ca/contribute/how-to-write-links#links-from-one-article-to-another

**Comment by DennisLee-DennisLee** [comment]
Thanks for the link. If I change a link from **~/Level2Dir/…** to **/RootDocName/Level2Dir/...**, the link navigation works in the code editor, but in preview it is still broken.

This is still better than the previous situation, since tilde link navigation failed in both the code editor and preview, so this issue is less important for me now. The preview still should be fixed, though (at least for one of those link types).

**Comment by bharney0** [comment]
@DennisLee-DennisLee I made a [PR](#662) which should handle tilde file resolution in preview. However, in my testing I noticed the code editor also had the same problem where the file path was not resolved when a tilde was used. Maybe we can make future changes to the code editor to handle this.

**Comment by DennisLee-DennisLee** [comment]
Thanks, @bharney0.
