### ISSUE TITLE
VSCode warns that docs-preview uses deprecated "vscode.previewHTML" API

### ISSUE THREAD

**Issue by MeikTranel** [microsoft/vscode-docs-authoring#138]
VSCode told me to file an issue 😄 

![image](https://user-images.githubusercontent.com/6466560/52573872-59607880-2e1b-11e9-9e67-4eecb63d420e.png)

**Comment by jamarw** [comment]
Hi @MeikTranel , thanks for the heads up.  Looping in @qinezh .

**Comment by bharney-msft** [comment]
Issue is currently in progress under PR #159

**Comment by jamarw** [comment]
An update has been shipped that addresses this issue.  Closing issue.
