### ISSUE TITLE
docs-markdown missing from docs-authoring-pack package.json

### ISSUE THREAD

**Issue by alexcnichols** [Microsoft/vscode-docs-authoring#14]
The pack installed correctly and installed the three extensions as I expect. However, if the docs-markdown extension is bundled in the pack, shouldn't it be listed in the externalDependencies of the package.json? What am I missing?

**Comment by alexcnichols** [comment]
The extension in the marketplace wasn't build from this source. 

https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-authoring-pack

This is what I find unzipping from the download link:
```
    "extensionDependencies": [
        "DavidAnson.vscode-markdownlint",
        "ms-docfx.DocFX",
        "docsmsft.docs-markdown"
    ]
```

**Comment by jamarw** [comment]
Hi @alexcnichols , thanks for letting us know.  I'll update the source.
