### ISSUE TITLE
Consecutive Alert blocks trigger MD028 error

### ISSUE THREAD

**Issue by nschonni** [microsoft/vscode-docs-authoring#141]
https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md028---blank-line-inside-blockquote
When 2 Alert style blocks are used next to each other, the MD028 rule gets triggered.
EX:
```md
> [!NOTE]
> My first note

> [!TIP]
> My second note
```

Not sure if this is more something for the "feedback" repo, but should this be flagged, or should authors be joining the NOTE/TIP together? Or will the processing allow for the space to be joined with a `>` and the authoring pack take that into account when inserting from the menu

**Comment by bharney0** [comment]
AB#227369

**Comment by bharney0** [comment]
@nschonni for now we decided to just disable the rule in docs-linting. If needed we can also add a setting to configure if docs-linting disables the rule or not. @adunndevster @lamebrain @jamarw
