### ISSUE TITLE
Can't preview files with special characters

### ISSUE THREAD

**Issue by nschonni** [Microsoft/vscode-docs-authoring#143]
EX: Docs:Preview fails for https://github.com/MicrosoftDocs/azure-docs/blob/216b19b475c7725b41aa008e86ea14cb808b329a/articles/active-directory/hybrid/reference-connect-sync-functions-reference.md
There are a few sets of odd characters in there that might be triggering it.
The error is toast that pops up is:
```
Unable to open 'view reference-connect-sync-functions-reference.md': [UriError]: Scheme contains illegal characters..
```

**Comment by jamarw** [comment]
Hi @nschonni , looping in @qinezh for help with this.  Thanks

**Comment by qinezh** [comment]
Will take a look, thanks for reporting it.

**Comment by nschonni** [comment]
Can't reproduce since the parser changed
