### ISSUE TITLE
Gauntlet should provide HTML source from markdown preview, in VS Code.

### ISSUE THREAD

**Issue by MightyPen** [Microsoft/vscode-docs-authoring#15]
1. Draft a .md file with content, by using VS Code. 
2. Click the Preview button on the Gauntlet tool bar. 
3. See an HTML render of the markdown content appear. 
4. Wish you could Copy the underlying HTML source code into your clipboard, or to file. 

5. Cry knowing Gauntlet does not offer such a Copy. 
6. Thank the Gauntlet people in advance, for them adding this Copy feature. Tell them that this need is often talked about in the hallway.  (Was vsts = 1234982.)

(MightyPen on GitHub, GeneMi@microsoft.com , 2018/04/12)

**Comment by adkinn** [comment]
@MightyPen what would you do with the HTML?

**Comment by MightyPen** [comment]
Examples:
I could send it in an .HTM file to my PM for review.
I could Print it on a printer for a hardcopy.

**Comment by MightyPen** [comment]
@adkinn Examples:
I could send it in an .HTM file to my PM for review.
I could Print it on a printer for a hardcopy.

**Comment by MightyPen** [comment]
@adkinn I was asked today what the status is on this Issue / feature request?  Do you have any information on this?  Thank you.

**Comment by adkinn** [comment]
@MightyPen I don't think it fits in with the use cases we are aiming to support. The HTML is transient and not guaranteed to be the same over time.
