### ISSUE TITLE
wrong extension name and typo in settings

### ISSUE THREAD

**Issue by meganbradley** [Microsoft/vscode-docs-authoring#16]
1. In VS Code, open User Settings and scroll down to find "Docs Authoring Extenstion Configuration".
2. Note that the extension name should be "Docs Markdown", and "extension" should be spelled correctly.

![image](https://user-images.githubusercontent.com/17304189/38703796-175c16c2-3e59-11e8-808e-aeca9be04ec4.png)

**Comment by jamarw** [comment]
Fixed in release 0.0.2.
