### ISSUE TITLE
Add support for PlantUml

### ISSUE THREAD

**Issue by cilerler** [Microsoft/vscode-docs-authoring#161]
It will be nice to have support for [PlantUml](http://plantuml.com/) where you may find more details in this [VSCODE Extension](https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml)

The code below should generate a graph

```
```plantuml
@startuml
'AutoInclude

scale 2

left to right direction
skinparam packageStyle rect
actor customer
actor clark
rectangle checkout {
    customer -- (checkout)

}

@enduml
```

Following code should not generate a graph and shows it as a code with color syntax
```
```plantumlcoode
@startuml
'AutoInclude

scale 2

left to right direction
skinparam packageStyle rect
actor customer
actor clark
rectangle checkout {
    customer -- (checkout)

}

@enduml
```

**Comment by lamebrain** [comment]
Sorry, this is not currently on the roadmap.
