### ISSUE TITLE
Add support for markdown-it extensions

### ISSUE THREAD

**Issue by cilerler** [Microsoft/vscode-docs-authoring#162]
I was going to create requests for each feature below but couldn't be sure if they are out of scope or not, so I created a single issue.  Please, let me know if you want me to create a separate request for each of those.  Unfortunately, without those, it is very hard to move forward with **docs**.

- table of contents
- footnote
- abbr
- deflist
- sup
- sub
- checkbox
- attrs
- kbd
- underline
- mark
- emoji
- containers

**Comment by lamebrain** [comment]
This feature would need to be implemented on docs before supporting in the Authoring Pack. It is not on the roadmap at this time.
