### ISSUE TITLE
Authoring pack embedding broken link

### ISSUE THREAD

**Issue by MashaMSFT** [Microsoft/vscode-docs-authoring#185]
Issue Type: <b>Bug</b>

i tried to add a bookmark, and this is what it added lol
[Migrate an on-premises database to an Azure VM](../../../../../../../Program Files/Git/azure-docs-pr/articles/virtual-machines/windows/sql/virtual-machines-windows-migrate-sql.md). 

Extension version: 0.1.2
VS Code version: Code 1.32.3 (a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4, 2019-03-14T23:43:35.476Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.90GB (16.79GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by MashaMSFT** [comment]
FYI, i just tried to upgrade to the latest version of VS code, and issue persists

VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)

**Comment by jamarw** [comment]
Hi @MashaMSFT , can you provide repro steps and the repo if possible?  Thanks

**Comment by MashaMSFT** [comment]
Hi @jamarw, i select the "insert bookmark" option in the docs authoring pack extension toolbar, i select "internal", i select my article, and then that's what gets inserted.
![image](https://user-images.githubusercontent.com/32783170/55922332-96e04880-5bb5-11e9-85d5-bef260012d94.png)

![image](https://user-images.githubusercontent.com/32783170/55922346-a1024700-5bb5-11e9-8339-5d7da433584f.png)

and this is the result
![image](https://user-images.githubusercontent.com/32783170/55922366-b8413480-5bb5-11e9-9476-fc13a7b2fd6d.png)

**Comment by MashaMSFT** [comment]
i figured out it was my fault, i was accidentally  was working on a file that was not in the repo :x thanks for your help!
