### ISSUE TITLE
Docs: Preview menu item not working after 0.1.2 release

### ISSUE THREAD

**Issue by nschonni** [Microsoft/vscode-docs-authoring#187]
Both Windows and OSX, selecting `Docs:Preview` stopped working around a week ago.
Alternate "Markdown: Preview" still works, so it seem related to the latest release.
Could also be related to the VS Code 1.33.0/1 release

**Comment by jamarw** [comment]
Hi @nschonni , thanks for bringing this up.  We're working on a fix and should have an update shortly.

**Comment by nschonni** [comment]
Thanks @jamarw, do you know if this because of #138 or something else?

**Comment by jamarw** [comment]
Hi @nschonni , that is the root cause.

**Comment by nschonni** [comment]
Ok, I'll close this as a duplicate of #138 then

**Comment by nschonni** [comment]
@jamarw just to confirm, it does now open with the latest release, but as you noted, custom things like `[!NOTE]` aren't rendering yet
