### ISSUE TITLE
Preview is not displaying DocFX specific  Notes

### ISSUE THREAD

**Issue by cblackuk** [microsoft/vscode-docs-authoring#200]
Related to the preview issue -> https://github.com/dotnet/docfx/issues/4406

Preview on old extension would render correctly like this:
![image](https://user-images.githubusercontent.com/28607803/56720081-e1c39980-6739-11e9-9613-57de8d8741d1.png)

But in this one it does that:
![image](https://user-images.githubusercontent.com/28607803/56720141-06b80c80-673a-11e9-8f04-6b8eb887f074.png)

Any chance it could be fixed? What is the point of having docs extension preview that does not render docs correctly?

**Comment by jamarw** [comment]
Hi @cblackuk , we are aware of the issue and we are working on a fix.  Thanks

**Comment by cblackuk** [comment]
Hi @jamarw, thanks for getting back to me. It would be great to get it fixed as we use it every single day and the old extension was very helpful in making sure DocFX formatting is correct.

**Comment by jamarw** [comment]
Hi @cblackuk , just a quick follow-up on this.  There is a PR open with additional updates to the preview extension that includes alert support so look for an update next week.  Thanks

**Comment by cblackuk** [comment]
Hi @jamarw  Thanks a lot! Cannot wait for that and I really appreciate you letting me know about it too.

**Comment by jamarw** [comment]
No problem @cblackuk , the update has been released.  Thanks

**Comment by cblackuk** [comment]
OMG it works!!! Thank you so much! @jamarw 
![image](https://user-images.githubusercontent.com/28607803/57277047-284eb780-709b-11e9-9b8f-8a2d81df497b.png)
