### ISSUE TITLE
New Preview doesn't hand xref links

### ISSUE THREAD

**Issue by nschonni** [microsoft/vscode-docs-authoring#207]
I think the old one had some logic added in https://github.com/Microsoft/vscode-docs-authoring/pull/109 but It looks like that doesn't work with the switch.
I believe there are some smarts in the xref links with the query string replacing the display text, but I'm not sure the previous one handled that

**Comment by jamarw** [comment]
Thanks @nschonni , I'll take a look.

**Comment by bharney0** [comment]
Xref should now resolve correctly with the newest version of docs-markdown. Change was made in PR #288
