### ISSUE TITLE
YAML front matter renders in DocFx preview

### ISSUE THREAD

**Issue by jasonjoh** [Microsoft/vscode-docs-authoring#22]
Opening the DocFx preview of a topic with CTRL+K, Q displays the YAML header. That should be hidden.

File used to reproduce: https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/quick-start.md

![image](https://user-images.githubusercontent.com/8966342/38735314-72f28a28-3ef6-11e8-8e11-397befe6081e.png)

**Comment by jamarw** [comment]
Hi @jasonjoh , I'll follow-up with the team about this and will add an update as soon as I have more information.  Thanks!

**Comment by jamarw** [comment]
Hi @jasonjoh , since this is a docfx-related issue I've create a new [issue](https://github.com/dotnet/docfx/issues/2684) in the docfx repo for tracking.  I'll close this issue as "moved".
