### ISSUE TITLE
DocFx preview doesn't properly handle tabbed conceptual

### ISSUE THREAD

**Issue by jasonjoh** [Microsoft/vscode-docs-authoring#23]
File used to reproduce: https://github.com/OfficeDev/outlook-dev-docs/blob/master/docs/add-ins/quick-start.md

That topic has two tabs, "Visual Studio" and "Any editor", with "Visual Studio" appearing first in the file. The second tab's contents don't render at all in the preview. The tabs themselves render as a bulleted list of links, but clicking the links does nothing.

![image](https://user-images.githubusercontent.com/8966342/38735581-2bc98f4c-3ef7-11e8-867f-4f8c551b6733.png)

**Comment by jamarw** [comment]
Hi @jasonjoh , I'll follow-up with the team about this and will add an update as soon as I have more information.  Thanks!

**Comment by jamarw** [comment]
Hi @jasonjoh , since this is a docfx-related issue I've create a new [issue](https://github.com/dotnet/docfx/issues/2683) in the docfx repo for tracking.  I'll close this issue as "moved". Thanks.
