### ISSUE TITLE
tab key is ignored

### ISSUE THREAD

**Issue by bc-ogawa-masakazu** [microsoft/vscode-docs-authoring#232]
Issue Type: <b>Bug</b>

After update VS code 1.35.1, Tab key input does't function.
If I removed this extention docs-markdown, the key works.

Extension version: 0.2.8
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (12.76GB free)|
|Process Argv|C:\Users\moono\Desktop\20190613FQ.md|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by cippero** [comment]
I'm getting this issue as well. When tabbing in front of a single line the tab is ignored, but when tabbing multiple lines, "undefined" is added in front of those lines instead.

Disabling the docs-markdown extension makes the tab key work again, and the issue only occurs on markdown files.

**Comment by jamarw** [comment]
@bc-ogawa-masakazu @cippero , thanks for reporting this.  We'll hop in and take a look.

**Comment by jamarw** [comment]
> @bc-ogawa-masakazu @cippero , thanks for reporting this. We'll hop in and take a look.

This has been fixed.  Thanks again for letting us know.
