### ISSUE TITLE
Should Microsoft Links cleanup handle download.microsoft.com?

### ISSUE THREAD

**Issue by nschonni** [microsoft/vscode-docs-authoring#236]
Got a suggestion on a PR for it over https://github.com/MicrosoftDocs/windows-itpro-docs/pull/4050/files#discussion_r294138135
I don't think the locale part applies, but it is probably one to convert to HTTPS as well

**Comment by bharney0** [comment]
Work is being done on this PR #449. We should be releasing shortly.
