### ISSUE TITLE
Partial incompatibility with vscodevim extension

### ISSUE THREAD

**Issue by bradumbaugh** [Microsoft/vscode-docs-authoring#24]
- OS: macOS 10.13.3
- Opened VS Code, uninstalled all extensions, clicked "Reload"
- Uninstalled VS Code using [AppCleaner](https://freemacsoft.net/appcleaner/)
- Downloaded/installed VS Code, version 1.22.2 (1.22.2), 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
- Opened a new file, entered some Markdown:
```
# This is a heading

This is some text

## This is another heading

This is some more text
```
- Saved the file: ~/Desktop/file.md
- Installed extension: vscodevim 0.11.3, clicked "Reload"
- In file.md
	- Moved cursor to top of file
	- Pressed `esc` to enter vim command mode
	- Pressed `/` to start a search
	- Typed `This` as the search value
	- Hit `enter` to complete the search text
	- Hit `n` multiple times to cycle through search results
	- Worked as expected
- Installed "Docs Authoring Pack" extension, clicked "Reload." This installed:
	- DocFX 0.1.1
	- Docs Authoring Pack 0.0.1
	- docs-markdown 0.0.1
	- markdownlint 0.14.1
- In file.md
	- Moved cursor to top of file
	- Pressed `esc` to enter vim command mode
	- Pressed `/` to start a search
	- Typed `This` as the search value
	- Hit `enter` to complete the search text
		- Instead of "completing" the search, `enter` inserts a newline in the file at the cursor's location (unexpected)
		- Since the search text hasn't been completed, typing `n` just appends "n" to the search text (rather than moving to the next search result as expected)
- Change filetype of document to plaintext (in lower-right corner of VS Code)
	- vim search works as anticipated
- Reverted document type to Markdown
- Disabled Docs Authoring Pack extension (only that extension, not its dependencies), clicked "Reload"
	- vim-style searching still broken
- Disabled docs-markdown extension, clicked "Reload"
	- vim-style searching works as expected

**Comment by mpepping** [comment]
Can confirm .. same behaviour here.

**Comment by jamarw** [comment]
Thanks @bradumbaugh and @mpepping for the information.  I'll start looking into this now.

**Comment by jamarw** [comment]
I think I know what's causing this.  The docs-markdown extension uses "enter" for the automaticList command.  We should be able to resolve this issue by checking to see if vim is active i.e. && !vim.active in keybindings.  I've tested this out and it appears to work as expected.  Will submit a PR and schedule this for the 0.0.3 release.

**Comment by jamarw** [comment]
Hi @bradumbaugh , @mpepping .  The fix for this was deployed with yesterday's release.  Please don't hesitate to let us know if you run into any other issues.  Thanks

**Comment by bradumbaugh** [comment]
Thanks @jamarw! Appreciate the help!
