### ISSUE TITLE
Don't use back slash in file path

### ISSUE THREAD

**Issue by qinezh** [Microsoft/vscode-docs-authoring#26]
In CommonMark, `\` in file link will be regarded as `%5C`, see [here](https://babelmark.github.io/?text=%5Bdemo%5D(root%5Cdemo.md)). 

To keep consistent with CommonMark syntax, please use `/` instead of `\` as path separator for file inclusion and code snippet syntax auto-completion.

**Comment by jamarw** [comment]
Thanks @qinezh , I will begin looking into this and ping with you questions if any arise.

**Comment by jamarw** [comment]
Hi @qinezh , just wanted to quickly follow-up on this.  A fix will be checked in early next week.  Thanks

**Comment by qinezh** [comment]
Awesome, good to know~

**Comment by jamarw** [comment]
Fixed in 0.1.0 release.
