### ISSUE TITLE
Line with a colon and the word zone/zones is flagged as a incorrect region

### ISSUE THREAD

**Issue by nschonni** [microsoft/vscode-docs-authoring#274]
The following line in a file gets flagged as a `docsmd.syntax: Syntax Linting. [Bad syntax for markdown extension. Begin with ":::".]`

```md
<a name="postal-code"></a> **Postal code**: A series of letters or numbers, or both, in a specific format, used by the postal service of a country/region to divide geographic areas into zones in order to simplify delivery of mail.
```

**Comment by bharney0** [comment]
Just tested this and I have been unable to repro the same issue. I believe this was fixed from some of the triple colon work. I am going to close this for now, let us know you still experience the issue.
