### ISSUE TITLE
Incorrect error and disabling the backspace key

### ISSUE THREAD

**Issue by guardrex** [microsoft/vscode-docs-authoring#282]
Occasionally when I open VSC (v1.36.1 currently), the docs-markdown extension (v0.2.12) throws an error when I use the backspace key, and the backspace key doesn't remove characters from the markdown file. Each time I press the key, the error message is ...

> The docs-markdown extension only works on Markdown files.

Sometimes the error clears itself in a minute or two. I can also clear it by closing and re-opening VSC.

**Comment by bharney0** [comment]
Thank you for reporting the issue. This problem has been fixed in by [removing the delete list helper](https://github.com/microsoft/vscode-docs-authoring/pull/339/files#diff-0bd763de7d6001c4ab04957287ce986aL364) functionality in this PR #339. Closing this issue out.
