### ISSUE TITLE
Configure indentation

### ISSUE THREAD

**Issue by mynormh** [Microsoft/vscode-docs-authoring#29]
Currently this extension doesn´t respect the global `editor.tabSize`. It always uses `"editor.tabSize": 4`

**Comment by nschonni** [comment]
❤️ to deferring to an EditorConfig file instead of a local developer setup

**Comment by jamarw** [comment]
Hi @mynormh , thanks for the feedback.  Flagging this as a DCR.  Please stay tuned for updates.

**Comment by jamarw** [comment]
Hi @mynormh , sorry for the delay on this.  We are looking into various scenarios to ensure these changes do not adversely affect parsing/publishing.

**Comment by meganbradley** [comment]
This has proven more tricky than expected because custom tab settings can cause publishing issues. Created internal [bug 78562](https://ceapex.visualstudio.com/Engineering/_workitems/edit/78562) to investigate further at a medium priority.

**Comment by winstonhenke** [comment]
@meganbradley any update on bug 78562? It looks to be a private AzD board. I'm still seeing this issue

**Comment by meganbradley** [comment]
The bug is closed as fixed. @jamarw @bharney can you take a look?
