### ISSUE TITLE
Extension causes VS Code Output window to show every time

### ISSUE THREAD

**Issue by gewarren** [microsoft/vscode-docs-authoring#294]
After I installed the docs-markdown extension in VS Code, the VS Code Output window appears at the bottom of the VS Code window every time I open VS Code and then open a markdown file. It's very annoying. Please don't open this window unless I left it open the last time VS Code was open.

![image](https://user-images.githubusercontent.com/24882762/63186443-45d3db80-c011-11e9-90fe-948fcf5064fd.png)

**Comment by jamarw** [comment]
Hi @gewarren, this was fixed in release 0.2.14 released on 8/21.  Thanks!
