### ISSUE TITLE
Add a Markdown link checker

### ISSUE THREAD

**Issue by nschonni** [microsoft/vscode-docs-authoring#30]
Not sure if this might be defered to DocFx to handle, but I've been using https://github.com/tcort/markdown-link-check on projects lately to validate that all those relative links in markdown are actually there.
That project has some downsides, so maybe you want to do your own:
- Gets flagged by DDoS protection on some sites
- Doesn't natively support globbing file patterns

**Comment by jamarw** [comment]
Hi @nschonni , thanks for the feedback.  Labeling this as a feature request for now and will pass this suggestion off to our PM team.  Please stay tuned for status updates.

**Comment by bharney0** [comment]
Link checker is being added in these PRs #350 and #349. Closing this issue out as these changes will be merged soon and the new extension will be added.
