### ISSUE TITLE
Preview doesn't indent code in lists properly

### ISSUE THREAD

**Issue by svick** [microsoft/vscode-docs-authoring#307]
When a list contains code block, the code is not shown correctly indented in the preview window.

For example, consider the following markdown:

```md
1. Some text.

    ```c#
    class C
    {
        void M();
    }
    ```
```

Here, `void M();` should show indented, but it doesn't:

![](https://user-images.githubusercontent.com/287848/63634554-60810280-c658-11e9-9739-8fad529517f8.png)

**Comment by jamarw** [comment]
Hi @svick , it looks like this issue has been fixed.  I just tried to repro in docs-preview version 0.3.36 and it worked as expected.  Please let us know if you run into any more issues.  Thanks
