### ISSUE TITLE
Opening DFM preview fails

### ISSUE THREAD

**Issue by cecilphillip** [Microsoft/vscode-docs-authoring#31]
OS: MacOS High Sierra
VS Code Version: 1.22.2
DocFX Extension version: 0.1.3

While working with files in https://github.com/MicrosoftDocs/sandbox, when I open try to view a DFM preview the extension fails with the follow error message
```
[Child process Error]: usage: chmod [-fhv] [-R [-H | -L | -P]] [-a | +a | =a [i][# [ n]]] mode|entry file ... chmod [-fhv] [-R [-H | -L | -P]] [-E | -C | -N | -i | -I] file ...
```

**Comment by jamarw** [comment]
Hi @cecilphillip , thanks for reporting this.  Did you happen to launch the preview using the DocFX extension keybindings or through the markdown extension UI?

**Comment by cecilphillip** [comment]
I tried opening it via the command palette `DocFx: Open DFM Preview`

**Comment by jamarw** [comment]
Thanks for confirming.  I've opened an [issue](https://github.com/dotnet/docfx/issues/2707) for this in the DocFx repo.  I'll close this one out but status can be tracked in the new issue.  Thanks @cecilphillip .
