### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by mlittlec** [microsoft/vscode-docs-authoring#336]
- Issue Type: `Performance`
- Extension Name: `docs-article-templates`
- Extension Version: `0.2.7`
- OS Version: `Windows_NT x64 10.0.18990`
- VSCode version: `1.38.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\mlittlec\docsmsft.docs-article-templates-unresponsive.cpuprofile.txt`
[docsmsft.docs-article-templates-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-docs-authoring/files/3678528/docsmsft.docs-article-templates-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by bharney0** [comment]
@mlittlec Thank you for reporting this issue. Unfortunately we could not reproduce this high cpu load after testing. Please provide additional detailed steps so we can help trouble shoot this problem.
