### ISSUE TITLE
docs-markdown: Inserting an image has changed

### ISSUE THREAD

**Issue by DavidFeldhoff** [microsoft/vscode-docs-authoring#337]
Hi all, please excuse in advance if this is a silly question, but I'm a markdown-newbie and hope you can help me:

I am using VS Code and the _docs-markdown_ extension to write markdown files which will become a static website using docfx.

Since a few days (since version 0.2.20 I think) the snippet to reference an image has changed. 
In version 0.2.19 it was:
`![alt text](images/test.jpg)`

Now it is:
`:::image type="content" source="images/test.png" alt-text="alt text":::`

The problem I'm facing is that it is not working with docfx anymore. As far as I can see [here](https://sourceforge.net/p/colon/wiki/markdown_syntax/#md_ex_img) the correct way to reference an image in markdown files was the first one. So my question is: Was it intended to change the snippet? If so, which tool can I use that is compatible with the new snippet?

Thanks and best regards
David

**Comment by MashaMSFT** [comment]
there's actually another issue also


Issue Type: <b>Bug</b>

I'm not sure when, but the docs authoring pack has changed the markdown format of images from normal linksk [linktext](linkpath.png) to this: 


   :::image type="content" source="media/virtual-machines-windows-portal-sql-create-failover-cluster-premium-file-storage/file-share-as-storage.png" alt-text="File share visible as storage in file explorer":::

Unfortunately, this is not a clickable link. Being able to click a picture, and then right-click it to reveal in explorer made finding images very easy. With the new format, there is no way to automatically open the image within vs code, and no way to reveal it in explorer. this makes finding images from within docs annoying and tedious. 

Extension version: 0.1.2
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:30:02.622Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v4 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (19.26GB free)|
|Process Argv|C:\Program Files\Git\sql-docs-pr\docs\toc.yml|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bharney0** [comment]
@DavidFeldhoff @MashaMSFT We just published an updated version of docs-markdown extension which includes the native markdown syntax for images `![alt text](images/test.jpg)` to keep the original functionality that was available in the previous versions.
![image](https://user-images.githubusercontent.com/51799435/66789722-b5473980-eea1-11e9-9c60-d8361f731df6.png)

Can you elaborate on the issue with docfx not working with the triple colon image syntax?

**Comment by DavidFeldhoff** [comment]
Thanks for the fix.
Regarding the issue with docfx: It is simply not working (see my attachment)
![image](https://user-images.githubusercontent.com/53570297/66802216-fe3bd400-ef1b-11e9-8d6f-7c714636549a.png)

**Comment by meganbradley** [comment]
@DavidFeldhoff if you're still experiencing this issue, can you provide full repro steps? I guess you're running docfx locally? This works in our standard build process.

**Comment by meganbradley** [comment]
@MashaMSFT can you elaborate on the difference you're seeing between the old and new image syntax? There shouldn't be any difference in the way the render on the published Docs page.

**Comment by DavidFeldhoff** [comment]
@meganbradley I don't have the problem anymore because I switched back to the normal image syntax (not the three colon one) which was working all the time. 
But I can try the three colon syntax once again with docfx. Will keep you up top date

**Comment by MashaMSFT** [comment]
@meganbradley my issue is that the new image link is no longer clickable within VS Code, I didn't even check to see how it renders on docs (though if I'm remembering correctly, it renders fine). With the previous syntax, the .png file was a clickable link *in VS Code* so you can click to open the image in a new tab, then right click the tab and reveal in explorer. This made it very easy to navigate to the image on the file system from within VS Code. Now, however, with the new image syntax, the image is not clickable, and so this benefit is gone. Now I have to manually navigate to the folder within file explorer, and it just takes more time, and is more tedious, then when this option was automatically available.

**Comment by meganbradley** [comment]
@MashaMSFT thanks for the clarification - I'll create a DCR for this. @lamebrain FYI.

**Comment by DavidFeldhoff** [comment]
@meganbradley I found the problem why the syntax with the three colons wasn't working.
It's the property `"markdownEngineName": "markdig"`.

If I add this one to my docfx.json file, the three colon syntax is working as well. Otherwise I get the output which I posted on October 15th. 

But I will stick to the old syntax due to the reasons @MashaMSFT  posted.
Or are there some advantages why we should use the three colon syntax?

**Comment by meganbradley** [comment]
@DavidFeldhoff the new syntax supports additional scenarios, including long descriptions for complex images, icons without alt text, and specifying a localization scope for the image that's different from the scope of the article that contains it. See this doc for more information: https://review.docs.microsoft.com/help/contribute/markdown-reference?branch=master#images

@MashaMSFT I filed this bug to address the non-clickable link issue:
https://ceapex.visualstudio.com/Engineering/_workitems/edit/142949

I think everything else is working as expected so I'll close this issue.

@lamebrain @bharney0 FYI.

**Comment by nschonni** [comment]
@meganbradley the review.docs.microsoft.com links aren't accessible for people outside of Microsoft
