### ISSUE TITLE
"command 'markdownQuickPick' not found" when attempting to open the authoring menu

### ISSUE THREAD

**Issue by Gnbrkm41** [microsoft/vscode-docs-authoring#343]
Title says all; Freshly installed the extensions pack, Attempting to open the menu through the command palette and `ALT+M` both results in the same error. 

From the developer tool console:
```
notificationsAlerts.ts:38 Error: command 'markdownQuickPick' not found
    at Proxy._tryExecuteCommand (commandService.ts:80)
    at r.then.i (commandService.ts:73)
onDidNotificationChange @ notificationsAlerts.ts:38
_register.model.onDidNotificationChange.e @ notificationsAlerts.ts:26
fire @ event.ts:580
addNotification @ notifications.ts:156
error @ notificationService.ts:56
onError @ commandsHandler.ts:332
setTimeout @ commandsHandler.ts:319
async function (async)
setTimeout @ commandsHandler.ts:310
setTimeout (async)
runAction @ commandsHandler.ts:303
run @ commandsHandler.ts:287
run @ quickOpenModel.ts:575
elementSelected @ quickOpenWidget.ts:561
_register.u.addDisposableListener.e @ quickOpenWidget.ts:235
```

Info from the VS Code About window:
```
Version: 1.39.1 (user setup)
Commit: 88f15d17dca836346e787762685a40bb5cce75a8
Date: 2019-10-10T23:31:28.683Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18999
```

I cannot seem to use any of the features since all of them only seem to be accessible through the menu.

**Comment by jamarw** [comment]
Hi @Gnbrkm41 , we haven't been able to repro this issue.  The extension is activated once a markdown file is opened in the active editor window so perhaps the extension hadn't started when you attempted to launch the quick pick menu.  Please let us know if you still hit the error after opening a .md file.  Thanks
