### ISSUE TITLE
add metadata nag options

### ISSUE THREAD

**Issue by meganbradley** [microsoft/vscode-docs-authoring#361]
1. I edit my topic in VS Code. 
2. I save my topic. 
3. Upon save, the Docs Markdown extension checks whether I have changed the value of ms.date. If not, I get a banner: "You have changed this file. Do you want to update ms.date with today's date?" 
   - If I select yes, ms.date is set to today's date in the correct format. 
   - If I select no, no change is made, and I am not asked again for this file in this VS Code session. 

This setting is enabled by default, but can be turned off in VS Code settings, e.g. "nag to update date = false".

Similarly, the extension checks the author and ms.author values against the values set in my settings (if applicable), and if they're different asks if I want to update them to my values.

Challenge: How to handle auto-save. Ask after file has been open for 2 minutes, and if dismissed don't ask again?

**Comment by nschonni** [comment]
An alternate/additional approach would be to have a third `auto` option, that would auto-update the date on save. I wouldn't suggest that as a default, and maybe you already discounted that as part of your internal discussions.

**Comment by IEvangelist** [comment]
I believe that we should rely on the `docfx.json` file for the `author`, `ms.author`, `ms.service`, and `ms.subservice` details as they will commonly exist as a glob pattern to desired default in docs repos. They are specified under the `fileMetadata` node - I'm trying to find time to work on this one.

**Comment by mamccrea** [comment]
We have the nag working for `ms.date`. Do we want nag options for the `author` values in the interim?

**Comment by IEvangelist** [comment]
> We have the nag working for `ms.date`. Do we want nag options for the `author` values in the interim?

Hi @mamccrea,

What does the nag do, could you share a screenshot? Curious about where it shows up and how it is actionable. I would imagine that content developers would appreciate the gentle reminder about the `ms.date` but not about the `author` -- that seems less likely to change.

**Comment by mamccrea** [comment]
@IEvangelist - I agree with your thoughts about an author nag. I’ll share a screenshot, too, but on save, the command palette drops down if the date is not today’s date and asks the user if they want to update the date. Enter for yes, esc for no.

**Comment by IEvangelist** [comment]
We already have tooling in place that could be used to update the `ms.date`, are you familiar with that?

https://docs.microsoft.com/en-us/contribute/docs-authoring/metadata-updates

**Comment by mamccrea** [comment]
Yes, I am familiar. The difference is that the nag option prompts the author on save instead of the author needing to remember to update the date, which was the request in this issue.

**Comment by bharney0** [comment]
The work has been completed to make this happen. Closing this issue out. Thanks @mevansgh1, nice work!
