### ISSUE TITLE
add insertion support for monikers (MVP)

### ISSUE THREAD

**Issue by meganbradley** [microsoft/vscode-docs-authoring#362]
1. Add a "Moniker" option to the Docs Markdown menu.
2. Add sub-options
- "range equals"
- "range greater than or equal"
- "range less than or equal"
3. Add behavior as follows _if cursor is in the YAML metadata block:_
- "range equals" inserts monikerRange metadata with value "= " and the cursor after the equals sign.
- "range greater than or equal" inserts monikerRange metadata with value ">= " and the cursor after the equals sign.
- "range less than or equal"  inserts monikerRange metadata with value "<= " and the cursor after the equals sign.
4. _If cursor is in the Markdown body of the file_, add a moniker block as follows with the specified operator (the example uses equals) and the cursor after the operator:

    :::moniker range="=":::

    :::moniker-end:::

**Comment by meganbradley** [comment]
A post MVP enhancement would be to pull available values via API from the Docs moniker service.

**Comment by bharney0** [comment]
work being done on PR #513
