### ISSUE TITLE
Docs Markdown cleanup scripts to find and remove unused images and includes

### ISSUE THREAD

**Issue by meganbradley** [microsoft/vscode-docs-authoring#363]
Under Cleanup, add a script to iterate through a cloned repo, find all images that aren't called from any article in the repo and move them to an "Unused images" folder outside the repo (under "Docs Authoring", similar to removed redirects). Log all removed image paths to the VS Code "Output" pane.

Add a similar option for unused included files.

**Comment by jamarw** [comment]
Hi @meganbradley , created a dev task for this.  Thanks!

**Comment by bharney0** [comment]
#430 Issue resolved with this PR
