### ISSUE TITLE
folder-level cleanup for Docs Authoring Pack

### ISSUE THREAD

**Issue by meganbradley** [microsoft/vscode-docs-authoring#364]
Currently the repo cleanup scripts only run on the whole repo, which can make for big PRs that don't make it through the PR review process. We should add the ability to select a folder in the repo and only run the selected script on that folder and its subfolders.

**Comment by jamarw** [comment]
Hi @meganbradley , created a dev task for this.  Thanks!

**Comment by bharney0** [comment]
#405 completed with this PR.
