### ISSUE TITLE
cleanup script - remove empty metadata attributes

### ISSUE THREAD

**Issue by meganbradley** [microsoft/vscode-docs-authoring#366]
Provide options to remove metadata with NULL and/or meaningless values from the YAML headers of Markdown files, e.g.:

ms.custom: 
ms.custom: ''
ms.devlang: ""
ms.devlang: na 
#ms.custom:

Menu item: "Cleanup > Empty Metadata

Sub-menu:
- Remove metadata attributes with empty values
- Remove metadata attributes with "na" or "n/a"
- Remove commented out metadata attributes
- Remove all

**Comment by jamarw** [comment]
Hi @meganbradley , created a dev task for this.  Thanks!

**Comment by bharney0** [comment]
#415 PR merged to resolve this issue.
