### ISSUE TITLE
support multi-select in Docs Authoring Pack

### ISSUE THREAD

**Issue by meganbradley** [microsoft/vscode-docs-authoring#367]
I’d like to request multi-select support in the Docs Authoring Pack for, for example, boldfacing text. In VS Code, you can press Alt to multi-select text. It would then be nice to be able to use DAP to bold all the selected text at once. (See attached screenshot of multi-select.)

![image](https://user-images.githubusercontent.com/17304189/70007387-016b3d80-1525-11ea-9669-b39423cad2ed.png)

**Comment by jamarw** [comment]
Hi @meganbradley , created a dev task for this.  Thanks!

**Comment by jamarw** [comment]
https://github.com/microsoft/vscode-docs-authoring/pull/401

**Comment by jamarw** [comment]
Functionality released in version 0.2.39
