### ISSUE TITLE
Add support for dark and high-contrast themes for preview

### ISSUE THREAD

**Issue by psignoret** [microsoft/vscode-docs-authoring#371]
It would be great to be able to preview with the "Dark" and "High contrast" themes as well as the current "Light" theme.

**Comment by jamarw** [comment]
Hi @psignoret ,

Thanks for the suggestion. A tracking ticket has been created for our team to review.  We'll update this issue once we have more information.

**Comment by jamarw** [comment]
https://github.com/microsoft/vscode-docs-authoring/pull/394

**Comment by jamarw** [comment]
Hi @psignoret , a preview update (v.0.3.39) that includes dark and high-contrast theme support has been released.  Thanks for the suggestion.
