### ISSUE TITLE
Alt text for "Docs: Image (Standard Markdown)" not working

### ISSUE THREAD

**Issue by burkeholland** [microsoft/vscode-docs-authoring#376]
When using the "Docs: Image (Standard Markdown)" command, value entered into the Alt text prompt is not persisted when the image is added to the document.

## Recreation steps

1. Open a Markdown file
2. Select "Docs: Image (Standard Markdown)" from the Command Palette
3. Enter "Test" as the alt text
4. Pick an image

### What Happens?

The image markdown is created, with `![](..image/path)`

### What should happen?

The image markdown is created with `![Test](../image/path)`

**Comment by DuncanmaMSFT** [comment]
@jamarw @adunndevster have you been able to repro this? I just tried and it produced

![Testing this alt text](../../public/android-chrome-192x192.png)
![Test](../../public/android-chrome-192x192.png)


Running 0.2.27 of docs-markdown

**Comment by bharney0** [comment]
@burkeholland We have been unable to repro this bug. Any other details that would help us trouble shoot? Please let us know what version of VS Code and docs-markdown extension you are running.

**Comment by burkeholland** [comment]
VS Code: 1.41.1
macOS:  10.15.2
Docs Markdown: 0.2.31

Repo Video...

https://msit.microsoftstream.com/video/d95568a4-9da2-4236-839f-0d72d4b24d3b

**Comment by jamarw** [comment]
Thanks for the video @burkeholland , I'll start debugging using macOS now.

**Comment by jamarw** [comment]
Hi @burkeholland , this should be fixed now in the latest release (0.2.32).  Thanks and please let us know if you run into any more issues.
