### ISSUE TITLE
markdocs tabbed content is not working on Win10x64 / vscode1.41.1

### ISSUE THREAD

**Issue by cresimpl** [microsoft/vscode-docs-authoring#395]
> [!WARNING]
> Markdocs preview is not working at all!
> 

> [!WARNING]
> Inside normal markdown preview tabbed content is not working!
> 

```
# [win](#tab/win)
tab content
# [lin](#tab/lin)
tab content
***
```

> [!IMPORTANT]
> My settings.json looks like below:
> ```
> {
>    "[markdown]":  {
>        "editor.quickSuggestions": true,
>        "editor.snippetSuggestions": "top"
>      },
>    "window.zoomLevel": 0,
>    "terminal.integrated.shell.windows": "C:\\windows\\System32\\wsl.exe",
>    "files.autoSave": "afterDelay",
>    "ansibleVaultInline.keyfile": "",
>    "ansibleVault.keypass": ""
> }
> ```

> [!IMPORTANT]
> vscode version info:
> ```
> Version: 1.41.1 (system setup)
> Commit: 26076a4de974ead31f97692a0d32f90d735645c0
> Date: 2019-12-18T14:58:56.166Z
> Electron: 6.1.5
> Chrome: 76.0.3809.146
> Node.js: 12.4.0
> V8: 7.6.303.31-electron.0
> OS: Windows_NT x64 10.0.18362
> ```

**Comment by bharney0** [comment]
@cresimpl Thank you for reporting this issue. Unfortunately we do not have tabbed conceptual functionality as of the latest release. However, we may look more into adding this functionality in the future. @meganbradley
