### ISSUE TITLE
Bulleted and numbered lists no longer auto-generate new entries

### ISSUE THREAD

**Issue by roygara** [microsoft/vscode-docs-authoring#409]
Noticed this when I updated to the latest docs authoring pack.

The behavior used to be that when you used the extension to create a bulleted list, it would provide the first "-" for you, and every time you pressed enter it would create another one. It no longer does that, you have to manually create each - yourself now.

Edit, I did a quick test, the same issue applies to numbered lists.

**Comment by meganbradley** [comment]
@jamarw IIRC there was a reason this stopped working? Can you pull some data about how often the list features are used? I'm wondering if it would make sense just to pull them from the menu if we can't create new list items automatically anymore.

**Comment by jamarw** [comment]
Hi @meganbradley , I'll look into this today to see what I can find.  Thanks

**Comment by bharney0** [comment]
@jamarw did you ever figure out what was going on with this one. Looking at past issues and this one came up.

**Comment by jamarw** [comment]
Hi @roygara , this issue has been fixed and is available in docs-markdown version 0.2.73. Thanks!

**Comment by roygara** [comment]
Thanks @jamarw , I appreciate the heads up! :)
