### ISSUE TITLE
Rewrite redirection urls in markdown files to new links at same time as redirect.json

### ISSUE THREAD

**Issue by nschonni** [microsoft/vscode-docs-authoring#41]
This may just be a small extension to #34 😉 
The description of the problem is https://github.com/MicrosoftDocs/feedback/issues/361, but to summarize, the redirect.json is great for published site (and I think now VS Code with your enhancement), but GitHub links have no concept of the redirect.
If at the same time as adding the redirect entry in the file, the existing usages of the redirect could be updated, then all versions would be happy.
This would also make #30 possible without a custom solution 😄

**Comment by meganbradley** [comment]
@nschonni 
This is a great suggestion and I've added it to our internal backlog. Thanks!
CC @jamarw

**Comment by meganbradley** [comment]
Created internal feature https://ceapex.visualstudio.com/Engineering/_workitems/edit/78578

**Comment by meganbradley** [comment]
We did some investigation into this and it proved to be more difficult than anticipated. We agreed to shelve the work for the current version of Docs and re-evaluate as part of upcoming global improvements.
