### ISSUE TITLE
Linking behavior mixup

### ISSUE THREAD

**Issue by roygara** [microsoft/vscode-docs-authoring#410]
Also noticed this after updating to the latest docs authoring pack.

The new link menu looks pretty good and it seems we got some extended functionality here, which is great! But I think some wires got crossed in the updates.

The behavior used to be: when using link to file in repo, it would simply take the article title. This makes sense because (as far as I know) standard practice is to take the article name for the link. But now it no longer does this, instead it prompts you for alt text, which you can ignore and it'll then populate with the name.

And now, when you choose to link to a web page, it doesn't prompt you for the alt text (it used to), instead it'll just automatically take the full URL and put that in for the display text as well. This doesn't make sense to me, since our standard practice was to use alt text instead of the URL for external links.

I think these two behaviors mistakenly got flipped but, if this is intentional, feel free to ignore this.

**Comment by bharney0** [comment]
@roygara thank you for reporting these 2 problems. We have file a bug in Azure DevOps to track the dev work. We should get to this within the next week or so. 

1. [Link to file in Repo Bug](https://dev.azure.com/ceapex/Engineering/_workitems/edit/180568)
2. [Link to web pack Bug](https://dev.azure.com/ceapex/Engineering/_workitems/edit/183067)

**Comment by jamarw** [comment]
Hi @roygara , this has been fixed in the latest release of the docs-markdown extension (v.0.2.57).  Thanks
