### ISSUE TITLE
Latest update broke another markdown preview extension

### ISSUE THREAD

**Issue by dan-wesley** [microsoft/vscode-docs-authoring#426]
was using the Dark (Visual Studio) theme. Basic black background with white text. The doc preview page was white background with black text. The colors for alerts such as Note or Important were what you see when the article goes live on docs.microsoft.com. After the automatic update the preview is now black with white text. The alerts are completely off color from what gets published. Need a workaround or how to go back a build. (Tried to use another preview extension (Github Styling) but the Doc Authoring Pack preview overrides it.)

**Comment by jamarw** [comment]
Hi @dan-wesley,

If you'd like to switch back in the meantime, VSCode does allow you to install a specific version of an extension.  If you open the extension pane, open docs-preview settings (gear), choose **Install Another Version** and select build 0.3.38 you'll get the previous experience.

Thanks

**Comment by dan-wesley** [comment]
That’s awesome, thank you!!

/**
* Dan Wesley (Experis)
*/

**Comment by jamarw** [comment]
No problem @dan-wesley.  We're looking into adding a setting so users can choose their preview theme.  I'll keep you updated.

**Comment by jamarw** [comment]
@dan-wesley Just wanted to follow-up on this.  The latest release of the docs-preview extension allows users to select static theme for preview.  Here's a [link ](https://github.com/microsoft/vscode-docs-authoring/tree/master/docs-preview#theme-support)to a demo video with the new functionality.  Thanks!

**Comment by dan-wesley** [comment]
@jamarw Thanks for the update, much appreciated.
