### ISSUE TITLE
Use full path for auto-completing links

### ISSUE THREAD

**Issue by jakrams** [microsoft/vscode-docs-authoring#43]
The number one feature I use from this extension is to insert links to other internal pages. It saves me so much time to auto-complete the proper relative link. However, it seems to have regressed a bit lately.

I have a lot of paths in my project that end with a file called "index.md", ie. "Topic/SubTopic/index.md". When I use ALT+m -> Link -> Internal and then type "SubTopic" for a couple of weeks I got "Topic/SubTopic/index.md" as a suggestion, and I could easily insert that link.

Lately this stopped working and I got NO suggestion at all anymore, not for that page, nor for any other page in that folder. The only way to get to that link is to type "index.md", but then I get hundreds of candidates, because my documentation is large any every folder has such a page.

I am not sure whether this was a change in VS Code or in the plugin, that changed the behavior, but it would make the plugin drastically more useful to me, if the old behavior would work again.

**Comment by jamarw** [comment]
Hi @jakrams , thanks for reporting this.  Can you please send us the version of VS Code as well as the version of the docs-authoring extension you're using?

**Comment by jamarw** [comment]
I believe this was caused by a change in the VS Code [api](https://github.com/Microsoft/vscode/issues/45589).  The quickpick options have not been expanded to allow for greater customization.  The matchOnDescription option should resolve this issues.

**Comment by jakrams** [comment]
VS Code version: 1.23.1
Docs Authoring Pack version: 0.0.2
docs-markdown version: 0.0.2

**Comment by jakrams** [comment]
I also noticed that the file open menu (CTRL+P) actually does filter the way that I would prefer it. Maybe it's just a matter of using the same settings as that thing?

**Comment by lamebrain** [comment]
Closing as a stale issue. Please open a new issue if this is still a problem.
