### ISSUE TITLE
Markdown Extension to render Helppage with MkDocs

### ISSUE THREAD

**Issue by dNsl9r** [microsoft/vscode-docs-authoring#434]
Hi there,
we just startet to write the Documentation for our Dynamics 365 Business Central Extension in MarkDown. 
My colleagues are using VS Code and installed your Extension to preview the Documentation in Microsoft Docs Style.

Rendering the Documentation to a static HTML Page is done by using MkDocs and a theme.
As things like [!TIP] is not recognized as a standard Markdown definition it just will be written as "[!TIP]".

When using MkDocs you can easily import 3rd Party Extensions like Markdown-LaTeX and so on. Is there any chance, that you provide your Docs Extension as Markdown Extension?

**Comment by bharney0** [comment]
Can you provide more information about what you mean when you ask if we can provide Docs Extension as Markdown Extension? We are currently using markdown-it and expanding on the existing functionality to extend the static output using plugins.

Our docs-preview extension/ Docs Styles uses a combination of [markdown-it plugin extensions](https://github.com/microsoft/vscode-docs-authoring/blob/f7056c0dd57e99e623f658a4e679058990913736/docs-preview/src/extension.ts#L42-L54) and [javascript on previewScript](https://github.com/microsoft/vscode-docs-authoring/blob/f7056c0dd57e99e623f658a4e679058990913736/docs-preview/package.json#L35-L44) to render an html preview that matches the Docs styles. The Docs Styles preview takes advantage of VSCodes built in previewScripts and markdown-it extensible plugins to make the preview work.

**Comment by dNsl9r** [comment]
@bharney Sure I'll try. I'm not THAT familar with all of these details, but I'll give my best ;-)
As we are using [MkDocs](https://www.mkdocs.org/) to create static websites based on Markdown.
MkDocs is internally using [Python Markdown](https://www.mkdocs.org/user-guide/configuration/#markdown_extensions) to translate Markdown to HTML. Python Markdown supports Extensions  as well ([see here](https://python-markdown.github.io/extensions/)).
It would be perfect if we could use your Extension in this Python Markdown - and therefore in MkDocs.

Do you think there is any chance?

**Comment by bharney0** [comment]
@dNsl9r unfortunately we are using [markdown-it ](https://github.com/markdown-it/markdown-it) for our markdown to HTML. And because of that, our extensions are only geared towards markdown-it. Our team does not anticipate we will be adding functionality that is compatible with Python Markdown. Sorry about that, and thank you for your interest.
