### ISSUE TITLE
I’m getting a ‘command insertImage no found’ error when I try to insert an image.

### ISSUE THREAD

**Issue by maggiesMSFT** [microsoft/vscode-docs-authoring#440]
That sums it up.  I select the Insert Image icon on the Docs Authoring ribbon, and I get a ‘command insertImage no found’ error when I try to insert an image. I tried reinstalled the authoring pack; same result. 
But other buttons still work, such as inserting links, or bold or italic.
What to do? 
thanks!

**Comment by bharney0** [comment]
@maggiesMSFT Thank you for reporting this issue. Sorry for any inconvenience and we are working on addressing this bug. This issue has been fixed with this PR #445. We will be releasing as soon as possible.

**Comment by maggiesMSFT** [comment]
Hi, @bharney0 -- thanks! Looking forward to the fix.
