### ISSUE TITLE
Constant Error Message When Editing Non-Markdown Files

### ISSUE THREAD

**Issue by acgritt** [microsoft/vscode-docs-authoring#441]
I don't know if this is related to Issue #282 or not but whenever I am editing a CSharp file in VSCode (v1.42.1) and docs-markdown (v0.2.51) is enabled an error message pops up saying:

> The docs-markdown extension only works on Markdown files.

If I close the pop-up and press the backspace key it comes back up. The backspace key isn't disabled, I just keep getting the message when working on non-markdown files.

**Comment by bharney0** [comment]
@acgritt Thank you for reporting the problem. There was a recent change that checks if the file is a markdown document on save. I think we can avoid the notification to reduce the noise. Work is being done on #442
