### ISSUE TITLE
Bookmark in this file issue

### ISSUE THREAD

**Issue by aablackm** [Microsoft/vscode-docs-authoring#45]
I have some clear H1 and H2 headers in my .md file but it keeps insisting that there are no headers in the file to bookmark to.

**Comment by jamarw** [comment]
Hi @aablackm , thanks for reporting this.  I'll take look and ping you if I need any additional information.

**Comment by jamarw** [comment]
Hi @aablackm , are you running into this issue on MacOS?

**Comment by aablackm** [comment]
I am not. I am running into it in Visual Studio Code on a Windows 10 Machine.

**Comment by jamarw** [comment]
OK, I can repro on MacOS but not on Windows.  Could you possibly share the .md file with me?  Thanks

**Comment by aablackm** [comment]
Well, I have good news. As of today I can't repro it either. For whatever reason everything seems to be working again. Thanks for investigating. If it happens again I'll send the file over.

**Comment by jamarw** [comment]
No problem, thanks for the update.

**Comment by jamarw** [comment]
Fixed in 0.1.0 release.
