### ISSUE TITLE
Add function to sort .openpublishing.redirection.json

### ISSUE THREAD

**Issue by nschonni** [Microsoft/vscode-docs-authoring#50]
Just noticed https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/sort-redir.py and thought maybe it was something other repo/authors might want too.

**Comment by meganbradley** [comment]
@nschonni 
This is a great suggestion and I've added it to our internal backlog.
CC @jamarw

**Comment by kraigb** [comment]
FYI, I wrote that script when I'd gone through the Visual Studio docs and consolidated all the redirects into the one file, because otherwise you have to search around every time you want to find redirects that affect a certain section of the docs.

**Comment by meganbradley** [comment]
@nschonni After talking to the Docs build team about this, we decided not to make these changes, which might have unexpected consequences given the way redirection works. They're looking at changing the way this works in the future, so they want to defer further investment until the next version.
