### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by sandrociceros** [microsoft/vscode-docs-authoring#510]
- Issue Type: `Performance`
- Extension Name: `docs-markdown`
- Extension Version: `0.2.61`
- OS Version: `Windows_NT x64 10.0.19587`
- VSCode version: `1.44.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Thinkpad corporativo\docsmsft.docs-markdown-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by bharney0** [comment]
@sandrociceros can you provide any additional details about when you experience the high cpu load, or scenarios where you no notice any slow down so we can help trouble shoot this problem?

**Comment by jamarw** [comment]
Hi @sandrociceros , just another follow-up on this.  Do you happen to have any additional details to help with troubleshooting?  Thanks

**Comment by bharney0** [comment]
More information is needed, closing this ticket out. We need the cpuprofile.txt to investigate further.
