### ISSUE TITLE
Cleanup... > Everything gets stuck at 99%

### ISSUE THREAD

**Issue by bharney0** [microsoft/vscode-docs-authoring#528]
When running everything, the program gets stuck at 99% complete and never finishes.

![image](https://user-images.githubusercontent.com/51799435/78387876-e2dd8780-7594-11ea-9ebf-e546c43b90f1.png)

**Comment by bharney0** [comment]
AB#227299

**Comment by adunndevster** [comment]
Could not reproduce.
