### ISSUE TITLE
Open file is automagically changed

### ISSUE THREAD

**Issue by diberry** [microsoft/vscode-docs-authoring#539]
When I open VSCode, or checkout a new repo/branch in VSCode, whatever file is open in the workspace is automatically changed by the Docs authoring pack for spaces, single quotes, and whatever other rules it has. It does this because the file is open in the workspace, not because I actually touched that file. 

This is a bug - the docs authoring pack shouldn't make any changes to a file just because it is open in the workspace. It needs to only make changes to the file after I have made changes to the file.

**Comment by bharney0** [comment]
@diberry This should be fixed now and was recently changed in #538 for smart quote and special character replacement. Please see version 0.2.64 of docs-markdown. This should no longer be the default to update special characters. If you still see this behavior can you uncheck the `Markdown: Replace Smart Quotes` setting, that should take care of it.

![image](https://user-images.githubusercontent.com/51799435/79369135-57091b00-7f05-11ea-8b1e-38930721b394.png)
![image](https://user-images.githubusercontent.com/51799435/79369168-625c4680-7f05-11ea-9d57-36ae390fbc26.png)
