### ISSUE TITLE
Add Vale to package bundle

### ISSUE THREAD

**Issue by nschonni** [Microsoft/vscode-docs-authoring#54]
https://valelint.github.io/docs/
Found a few issues running the VS Code plug-in (like duplicate words), but it currently only does the whole workspace and can fail on some large repositories.

**Comment by meganbradley** [comment]
@nschonni 
Thanks for the suggestion! We generally don't encourage users to run QA on full repos and submit large PRs - it's against our workflow. There's no reason users can't install this extension but we don't want to include it in our pack for that reason. CC @jamarw

**Comment by nschonni** [comment]
May have been wrong about the only the whole workspace thing. It seems like the only "command" is for the whole workspace, but I think it does run on individual files for the Issues tab
