### ISSUE TITLE
Add Moniker to quick-pick-menu-controller.ts

### ISSUE THREAD

**Issue by bharney0** [microsoft/vscode-docs-authoring#546]
We have recently added a `Docs: Moniker` option to the `F1` command pallet. However, it is missing in the markdown quick pick that is accessible using `Alt + M`. We need to add the Moniker option to the markdown quick pick options. 

We should use `Moniker` as the quick pick option title, and the icon should be octicon-project https://octicons.github.com/icon/project/ using `$(project)`

**Comment by mamccrea** [comment]
@JohnTheFarmer
