### ISSUE TITLE
Images in markdown

### ISSUE THREAD

**Issue by egorzainullin** [microsoft/vscode-docs-authoring#559]
I am not sure that it is a bug, but when you use such syntax for adding image

`:::image type="content" source="<folderPath>" alt-text="<alt text>":::`

For example,
`:::image type="content" source="initialBlock.png" alt-text="ds":::`
it is shown correcly in Preview

But if alt-text is written in local language, for example, in my case
`:::image type="content" source="initialBlock.png" alt-text="бла-бла":::`
It's shown as raw code

But it works correctly for syntax like that `![<alt text>](<folderPath>)`
`![бла-бла](initialBlock.png) `

**Comment by bharney0** [comment]
@egorzainullin Thank you for reporting this issue. We have been able to repro the problem and will be looking into a fix.

**Comment by bharney0** [comment]
This bug has been fixed in PR #565. The changes should be released to production this week, and you can anticipate that docs-preview version `0.3.48` should work with local languages. Thank you for reporting the problem. Please let us know if you have any further feedback.
