### ISSUE TITLE
Docs: Cleanup "empty metadata" breaks files in https://github.com/dotnet/docs

### ISSUE THREAD

**Issue by nschonni** [microsoft/vscode-docs-authoring#577]
Running on the repo, it's changes sections of code samples, and non-single value parts of front-matter. This might be a good repo to test for regressions on.

**Comment by bharney0** [comment]
@nschonni, Thank you for reporting the problem. We we will take a look at this repo and resolve the issue so only the yaml frontmatter is affected.

**Comment by bharney0** [comment]
AB#227297

**Comment by bharney0** [comment]
@nschonni  this issue should be resolved by the linked PR #558. Please let us know if you see more instances of this issue.
