### ISSUE TITLE
Preview extension constantly edits files when I open them, but with no visible changes.

### ISSUE THREAD

**Issue by Thraka** [microsoft/vscode-docs-authoring#580]
I've tracked this problem down to the preview extension. If it's enabled I get updates to most files when I first open them. There is no visible change detected by git.

Pretty much any file I open here causes the issue to appear

https://github.com/dotnet/docs/tree/master/docs/framework/additional-apis

![files-auto-changed-1](https://user-images.githubusercontent.com/2672110/81962229-4c0ade80-95c8-11ea-9251-ad090fc7d937.gif)

**Comment by bharney0** [comment]
@Thraka thank you for reporting the problem. We will look into the issue and let you know what we found.

**Comment by bharney0** [comment]
AB#227289
