### ISSUE TITLE
Would you consider adding another "Markdown extension" to the docs-linting VSCode extension?

### ISSUE THREAD

**Issue by seesharprun** [microsoft/vscode-docs-authoring#583]
Today, your extension performs linting and the [DOCMS004 linter rule](https://github.com/microsoft/vscode-docs-authoring/blob/85f2244dededd80ad6b7c49a753030a9437cef14/docs-linting/markdownlint-custom-rules/common.js#L13) only allows the following Markdown extensions:
- zone
- moniker
- row
- column
- form
- no-loc
- image
- code

This extension is useful for authoring so many different Markdown documents, not just docs.com but tools, like Pandoc, allow the use of other Markdown extensions. Specifically, Pandoc allows you to use **notes** as a Markdown extension with the following syntax:

```
::: notes

Content

:::
```

Today, I have my team write documentation and presentations using Markdown and produce them using Pandoc. This one omission is the only difference I could find. Since I could not find a way to ignore the **DOCSMD004** rule, I'm stuck with an all-or-nothing proposition to either stop using your VS Code extension or accept that it will always show errors for that single Markdown extension. Eventually, I'm tracking #212 so I can implement your rules in my CI process on GitHub.

Before I created a PR, I wanted to see if proposing a new Markdown extension violates any rules or plans your team has for the **docs-linting** extension.

> *Sorry about the multiple "extensions". It's so confusing that it refers to both Markdown and VSCode in this context 😆*

**Comment by bharney0** [comment]
I dont think this would violate any rules we have. We have a [regex that defines the allowed triple colon attributes](https://github.com/microsoft/vscode-docs-authoring/blob/21978383c3b08987eda29ccf4f972dedce4d3d5e/docs-linting/markdownlint-custom-rules/common.js#L11). I dont see any problem with adding note. Feel free to contribute by adding note to the regex and I'll go ahead and approve.
