### ISSUE TITLE
Insert link in TOC files no longer works

### ISSUE THREAD

**Issue by roygara** [microsoft/vscode-docs-authoring#601]
Hey all,

I've noticed that for the past several...weeks/months, insert a link when in a TOC.yml file no longer works. I can activate it but it no longer brings up the prompt allowing you to enter/search for a filename. Once you select insert link, it just goes away and never brings up the second prompt.
![insert link](https://user-images.githubusercontent.com/31490067/82712993-54a18b80-9c3e-11ea-91d5-ce4422203bad.png)

Would someone look into this? It was a big value add.

**Comment by bharney0** [comment]
@roygara, thank you for reporting this problem. We will take a look into the issue and get it fixed.

**Comment by bharney0** [comment]
AB#227286
