### ISSUE TITLE
Greeting with error under Remote-WSL

### ISSUE THREAD

**Issue by hermes85pl** [microsoft/vscode-docs-authoring#605]
Every time I start Remote-WSL, even without opening any project I get an error message:

> [docsmsft.docs-markdown]: Menu item references a command `applyTemplate` which is not defined in the 'commands' section.

The extension used to work fine under Remote-WSL before.

**Comment by bharney0** [comment]
AB#230020

**Comment by sanket-bhalerao** [comment]
getting the same error.
i started getting this error after installing 'docs-markdown' extension.

**Comment by jamarw** [comment]
Hi @hermes85pl , this error has been fixed in release 0.2.74.  Thanks!
