### ISSUE TITLE
Lightbox format breaks when alt-text is used.

### ISSUE THREAD

**Issue by roygara** [microsoft/vscode-docs-authoring#608]
For whatever reason, when the new docs markdown is used (the plugin no longer allows for old markdown, though you can write it by hand of course) alt-text is broken, it displays as a caption for the lightbox image.

Our new syntax works fine for regular images, just not the new syntax. Also the magnifying glass is incorrectly placed, I didn't get an image of it here but it gets kicked up to where the sentence above the image is, instead of actually on the image where it's supposed to be. I added an image of me using the actual MD formatting instead of ours, to illustrate it works fine, on that image I added a box where our MD displays the magnifying glass.

I'm guessing our MD is just translating the alt-text wrong, somewhere. Since it displays as a caption instead of as alt-text.

See attached images for examples:
![Broken-alt-text](https://user-images.githubusercontent.com/31490067/83463764-d0ac8800-a423-11ea-8e00-3c2611758952.png)
![alt-text](https://user-images.githubusercontent.com/31490067/83463787-dd30e080-a423-11ea-84cc-535bb18ec44b.png)
![magnifying-glass-gets-shoved-up-here-for-some-reason](https://user-images.githubusercontent.com/31490067/83463966-63e5bd80-a424-11ea-9e3e-60b4cecbbecf.png)

Edit: I'm also attaching the relevant PR. Just to illustrate that our PR reviewers will block on this bug. So if anyone is using lightbox, they have to manually construct the original MD syntax instead of the docs MD syntax provided by the plugin. https://github.com/MicrosoftDocs/azure-docs-pr/pull/116862

**Comment by bharney0** [comment]
@roygara Thank you for reporting the problem. We will look into it as soon as possible. Please see the Azure Boards task AB#231473

**Comment by lamebrain** [comment]
This is fixed.
