### ISSUE TITLE
[!VIDEO] format causes MD034 (bare links) to be triggered in latest extension

### ISSUE THREAD

**Issue by nschonni** [microsoft/vscode-docs-authoring#641]
Since these insert raw urls, the MD034 rule gets triggered in MSDocs repos

Aside: I believe there is supposed to be a triple colon version of these embeds, but I haven't found it by either typing `:::`, and the `Docs: Video` inserts the Blockquote styel

**Comment by lamebrain** [comment]
The triple colon video extension is in the works. We'll tidy up that rule during release. Thanks!
