### ISSUE TITLE
Wrong preview when use quote along with latex

### ISSUE THREAD

**Issue by XQDD** [microsoft/vscode-docs-authoring#642]
# vscode default
![image](https://user-images.githubusercontent.com/20871761/84854641-bbc32c00-b094-11ea-9198-f39b84e84696.png)

# docs preview
![image](https://user-images.githubusercontent.com/20871761/84854651-c251a380-b094-11ea-9a49-8bdefd3b4103.png)

[AB#239506](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/239506)

**Comment by bharney0** [comment]
@XQDD this issue should be resolved with the PR #705 Please let us know if you are still experiencing this issue.
