### ISSUE TITLE
docs-metadata removes all quotes

### ISSUE THREAD

**Issue by garyericson** [microsoft/vscode-docs-authoring#660]
I used the **docs-metadata** to change a single metadata value, but all the quote marks in the metadata block got removed in the result. This caused multiple build errors.

I used the **Extract** command to extract a single metadata value (ms.technology) in ~100 articles. The Extract command created a csv with only ms.technology values for each article. I changed those values and ran the **Apply** command against the CSV. The Apply command updated the ms.technology value, but it also removed all the quote marks in the metadata blocks. This caused build warnings for articles with ":" in the title and (I believe - it's hard to tell from the build errors) for monikerRange values in all articles.

Here's an example original metadata block:
```
---
title: "R tutorial: Feature engineering"
description: Tutorial showing how to create data features using SQL Server functions for in-database analytics.
ms.prod: sql
ms.technology: machine-learning
ms.date: 11/26/2018  
ms.topic: tutorial
author: dphansen
ms.author: davidph
ms.custom: seo-lt-2019
monikerRange: ">=sql-server-2016||>=sql-server-linux-ver15||=sqlallproducts-allversions"
---
```

I changed only ms.technology, and got this result - this title (and maybe monikerRange) caused a build error:
```
---
title: R tutorial: Feature engineering
description: Tutorial showing how to create data features using SQL Server functions for in-database analytics.
ms.prod: sql
ms.technology: machine-learning-services
ms.date: 11/26/2018  
ms.topic: tutorial
author: dphansen
ms.author: davidph
ms.custom: seo-lt-2019
monikerRange: >=sql-server-2016||>=sql-server-linux-ver15||=sqlallproducts-allversions
---
```

[AB#242352](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/242352)

**Comment by adunndevster** [comment]
@garyericson - I just pushed an update to fix this issue. Please let me know what results you get!

**Comment by garyericson** [comment]
I just tried it, and it didn't seem to do anything. I did this:

1. View -> Command Palette -> Docs Metadata Extract
2. Selected a folder in the repo
3. Entered "ms.topic" for the tag
4. Got this message:
   ![image](https://user-images.githubusercontent.com/2539867/92979265-f7c51d80-f446-11ea-925e-09d47f467c7e.png)
5. Clicked OK

Nothing happened - no CSV file opened and I don't get a pop-up message after the one above. I found a "Docs Authoring" folder in my user folder, but there's nothing in it except an empty "metadata" folder.

Am I doing something wrong?

**Comment by garyericson** [comment]
The version of docs-metadata that I have is 1.0.5.

**Comment by Paul-Dempsey** [comment]
Missing CSV is: https://github.com/microsoft/vscode-docs-authoring/issues/762

**Comment by garyericson** [comment]
CSV is working, and quotes are working. Thanks!
