### ISSUE TITLE
Markdown Preview: Alert (Note, Important, etc) boxes aren't rendering in preview when text is mixed-case

### ISSUE THREAD

**Issue by JasonWHowell** [microsoft/vscode-docs-authoring#672]
There is a bug in the Preview of alert boxes. It shouldn't be as case sensitive. 

The docs site allows for mixed case in the Note/Tip/Caution/Important/Alert markdown callout, but the Docs Authoring Pack Preview isn't consistently rendering those. We should relax the casing requirement to match docs.microsoft.com rendering.

The page looks fine on the docs site:
https://docs.microsoft.com/en-us/azure/marketplace/partner-center-portal/pc-saas-fulfillment-api-v2

In the preview, the mixed case / lowercase Note is broken 
```
>[!Note]
>The publisher will not get notified of the SaaS purchase until the customer initiates the configuration process from Microsoft side.
```
![image](https://user-images.githubusercontent.com/5067358/86419421-ef52a880-bc87-11ea-9c32-0fe7ba7448d3.png)

Uppercase works
```
>[!NOTE]
>The publisher will not get notified of the SaaS purchase until the customer initiates the configuration process from Microsoft side.
```
![image](https://user-images.githubusercontent.com/5067358/86419478-1f01b080-bc88-11ea-9512-45bc1329ed0e.png)

[AB#247163](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/247163)

**Comment by JasonWHowell** [comment]
FYI @mamccrea

**Comment by jamarw** [comment]
Hi @JasonWHowell , this issue was fixed in docs-preview v.0.3.53. Thanks!
