### ISSUE TITLE
Docs Authoring pack doesn't support all code block formatting

### ISSUE THREAD

**Issue by SnehaGunda** [microsoft/vscode-docs-authoring#677]
When using the docs authoring pack, after typing the code format, the dropdown that appears doesn't show console and shell format. 
 

![image](https://user-images.githubusercontent.com/14284405/87186601-a199f980-c2a0-11ea-91d8-eb9fedc28922.png)

[AB#265566](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/265566)

**Comment by lamebrain** [comment]
Hi @SnehaGunda, thanks for the input. There is an ongoing effort to standardize devlangs and other metadata through a taxonomy service. Once that's available, we'll get that integrated.
