### ISSUE TITLE
Search Engine Preview broken with error "EISDIR: illegal operation on a directory, read"

### ISSUE THREAD

**Issue by JasonWHowell** [microsoft/vscode-docs-authoring#679]
When I try to use "Search Results Preview" it doesn't function any more. 

Command 'Docs: Search Results Preview' resulted in an error (EISDIR: illegal operation on a directory, read)

[AB#265722](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/265722)

**Comment by JasonWHowell** [comment]
This is the last file access I see before the error pops up
C:\git\partner-center-pr\partner-center\.vscode\cSpell.json

Using process monitor to monitor code.exe while trying a search preview.
7:30:55.3470943 PM	Code.exe	11712	CreateFile	C:\git\partner-center-pr\partner-center\.vscode\cSpell.json	PATH NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
7:30:55.3475032 PM	Code.exe	11712	CreateFile	C:\git\partner-center-pr\partner-center\cSpell.json	NAME NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
7:30:55.3479801 PM	Code.exe	11712	CreateFile	C:\git\partner-center-pr\partner-center\.vscode\cspell.json	PATH NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
7:30:55.3481319 PM	Code.exe	11712	CreateFile	C:\git\partner-center-pr\partner-center\cspell.json	NAME NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
7:30:55.3481879 PM	Code.exe	11712	CreateFile	C:\git\partner-center-pr\partner-center\.cspell.json	NAME NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a

**Comment by bharney0** [comment]
@JasonWHowell thank you for reporting this issue. I used your example file in the partner-center-pr repo to check that referral.md now works with SEO Preview and were all good. Should be deploying these changes this week. Sorry for the delay in getting this fixed.

**Comment by JasonWHowell** [comment]
Nice work. Thanks @bharney0 

Maybe this is an edge case - let me know if something is wrong in the partner center repo, in case I need to fix it for other reasons. Maybe something with docfx.json location, or the breadcrumb.yml. Or could be that folders are nested differently in this repo.

**Comment by bharney0** [comment]
@JasonWHowell it was actually the breadcrumb file that the docfx file was pointing to was not found. It was breadcrumb/toc.json, but the toc file was actually a yaml file. This was throwing an error and causing the whole program to terminate early before rendering.
