### ISSUE TITLE
can this plugin be used to validate other types of schemas?

### ISSUE THREAD

**Issue by dcsan** [microsoft/vscode-docs-authoring#693]
the repo linked in the README is also not there now:

https://github.com/MicrosoftDocs/schemas

I was hoping to have some local schema files in my own repo and validate a bit similar to the redhat plugin

[AB#275001](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/275001)

**Comment by lamebrain** [comment]
Hi @dcsan, here's the updated url for the schemas: https://static.docs.com/ui/latest/schemas/schema_config.json

Thanks!
