### ISSUE TITLE
Feature Request: Please add support for Mermaid syntax in Markdown documents

### ISSUE THREAD

**Issue by Glober777** [microsoft/vscode-docs-authoring#701]
It would be really great if the extension would support [Mermaid syntax](https://mermaid-js.github.io/mermaid) for Markdown documents (syntax highlight, linting and preview). That would make it much easier to work with diagrams included in Markdown files that are used for Wiki pages that are published through Azure Repos (support for Mermaid has been added to Azure DevOps in [Sprint 158](https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/wiki/sprint-158-update)).

[AB#277639](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/277639)

**Comment by Paul-Dempsey** [comment]
Not sure that anything but docs.microsoft.com is the target support for the docs authoring extensions. There are a number of open issues that boil down to the same question about supporting other markdowns and publishing systems (ADO, GitHub, mostly)

**Comment by meganbradley** [comment]
This is out of scope for the foreseeable future.
