### ISSUE TITLE
Docs preview does not render zones

### ISSUE THREAD

**Issue by therealjohn** [microsoft/vscode-docs-authoring#708]
It's difficult to author docs that use zones because the preview feature does not show the UI as it would appear once published. 

For example, consider this:

```
:::zone pivot="windows"
// some VS content
:::zone-end
:::zone pivot="win-vs2017"
// some 2017 content
:::zone-end
:::zone pivot="macos"
// some macOS content
:::zone-end  
``` 

I'd expect the preview to render this at the top and it behave similarly to what shows up when published
![image](https://user-images.githubusercontent.com/1501196/89417962-6521b800-d6fd-11ea-8c64-9eaf22aa52e0.png)

[AB#280461](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/280461)

**Comment by meganbradley** [comment]
This will be included in build-based local preview. ETA FY21 H2.
