### ISSUE TITLE
Replace smart quotes feature should not replace characters in code fence

### ISSUE THREAD

**Issue by sdwheeler** [microsoft/vscode-docs-authoring#711]
This feature was added in #429 but it is not listed in the [change log](https://github.com/microsoft/vscode-docs-authoring/blob/master/docs-markdown/changelog.md).

The feature does a global replace of all mapped characters, including characters inside of markdown code blocks and code spans. Text inside of code fences should be treated as literal text and should not be changed.

I ran into this problem recently when updating this [article](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/docs-conceptual/dev-cross-plat/vscode/understanding-file-encoding.md). This article talks about character encoding issues and includes character examples that are replaced by this feature. All the example characters are contain in code fences. The article is explicitly trying to show what happens when you don't use the correct character encoding. We need to show these characters as they are presented in real life.

For example:

> an en-dash (`–`) appears as the characters `â€"`

gets changed to:

> an en-dash (`–`) appears as the characters `â&euro;"`

cc: @IEvangelist 

[AB#281117](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/281117)

**Comment by IEvangelist** [comment]
Hi @sdwheeler - hope all is well. This feature defaults to `off`, and is an exclusive opt-in feature. To turn it `off`, follow [these steps here](https://review.docs.microsoft.com/en-us/help/contribute/docs-authoring/smart-quote-replacement?branch=master#preferences). I was already aware that it replaced text in code fences, I simply haven't had the bandwidth to fix that yet. For now the workaround is to disable this, and only toggle it on when you need it. Sorry for the inconvenience.

**Comment by sdwheeler** [comment]
@IEvangelist, thanks. I knew about the configuration switch and turned it off.
