### ISSUE TITLE
keep say `Click to fix unrecognized "diff" code fence language identifer` in show fixes bulb

### ISSUE THREAD

**Issue by NewUserHa** [microsoft/vscode-docs-authoring#724]
never see has this feature in the doc.
and 
never see a switch to turn this off.

please fix

[AB#287911](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/287911)

**Comment by Paul-Dempsey** [comment]
Can you provide an example of what you're trying to do?

**Comment by NewUserHa** [comment]
![image](https://user-images.githubusercontent.com/32261870/96180662-59f0d100-0f65-11eb-981c-60a2f877b9f0.png)
text -> diff also pops

**Comment by meganbradley** [comment]
This is by design because text isn't an approved language code.

**Comment by Paul-Dempsey** [comment]
what do you use for text that must be presented as <pre> but doesn't fall into any of the predefined buckets?

**Comment by NewUserHa** [comment]
`diff ` can't work too

**Comment by meganbradley** [comment]
@Paul-Dempsey the recommended value for plain text is "console". But note that the VS Code Warning is just informational at this time as we work on updating the taxonomy.

**Comment by Paul-Dempsey** [comment]
If I read the question correctly, the original issue here is that they're needing to show a file diff example. 
A snippet labelled "Console" probably isn't appropriate for such an example.

**Comment by meganbradley** [comment]
@Paul-Dempsey @NewUserHa 
The warning is just informational at this time, so it won't actually block you from adding anything you want. Internal users can contact the Docs IA team for advice/to request additional values. See the taxonomies list in the Docs Contributor Guide for more information.
