### ISSUE TITLE
format of image file for DevOps wiki "![Text](URL)"

### ISSUE THREAD

**Issue by rfoster12** [microsoft/vscode-docs-authoring#734]
i am using the authoring pack to create content for a DevOps wiki.  the syntax for displaying an image file in DevOps is ![Text](URL), however the format produced in the Doc Authoring pack is :::image type="content" source="../.images/image.jpg" alt-text="test":::.

Is there any way to configure this tool for the other format?  Any one have any suggestions?

[AB#294035](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/294035)

**Comment by Paul-Dempsey** [comment]
Docs Authoring pack is designed for docs.microsoft.com (Open Publishing System), and not for general markdown authoring for other markdown flavors (ADO, GitHub, etc.), so this is likely As Designed. The team might consider taking a contribution, but might not want to take on the maintenance and support burden of an expanded scope of features.

**Comment by DavidFeldhoff** [comment]
As far as I know Microsoft uses docfx for docs.microsoft.com - at least for Dynamics 365 Business Central: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/help/contributor-guide#build-html-files

So we wanted to do that as well. And this extension already had the image syntax ! [Alt Text] (Path to file) once in an older version, but switched to the ::: syntax. Unfortunately, docfx can't work with the ::: syntax. I'd love to have a possibility to use the other one as well.

**Comment by lamebrain** [comment]
Yes, thanks @Paul-Dempsey, `:::image` is the current standard for creating images in Docs and unfortunately we do not have plans to support alternate formats at this time.
