### ISSUE TITLE
No metadata extract .csv file

### ISSUE THREAD

**Issue by maggiesMSFT** [microsoft/vscode-docs-authoring#762]
Hi, @general -- I'm trying to run the metadata report for my repo. I select the Settings cog > Command Palette > Docs: Metadata Extract. 

I’m looking at this article, https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-metadata
I don't specify any metadata, just hit return, because I want it all.
Where does the file go? I get the Extracting... toast. Eventually I click OK.  
Where did the file go?
I go to my C:\Users\username\Docs Authoring\metadata folder. My past metadata extractions are there, but not this one. What am I missing? 
Thanks!

[AB#318124](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/318124)

**Comment by adunndevster** [comment]
Hi @maggiesMSFT - What OS, and repo are you working with?

**Comment by maggiesMSFT** [comment]
Hi, @adunndevster -- Windows, and the Power BI repo, powerbi-docs-pr.

**Comment by adunndevster** [comment]
Thanks @maggieMSFT, I will dive in!

**Comment by maggiesMSFT** [comment]
Great, thanks @adunndevster !

**Comment by garyericson** [comment]
Tagging myself to follow this -- this hasn't worked for me either since Sept. (see Issue #660 from 9/11/20)
@garyericson

**Comment by SerdarSoysal** [comment]
+1 to this. Metadata tool was essential for managing bulk updates. Having it be not functional is super disruptive. Any updates on this?

**Comment by meganbradley** [comment]
Tracking in this bug assigned to @adunndevster: https://dev.azure.com/ceapex/Engineering/_workitems/edit/318124

**Comment by adunndevster** [comment]
@SerdarSoysal @garyericson - Can you try updating your docs-metadata extension (should update to 1.0.6) and see if it resolves your issue?

**Comment by garyericson** [comment]
@adunndevster - That worked for me. I had .NET 3.1 installed and I had to install 2.1 for it to work, but it created the CSV file for me.

Thanks!

**Comment by adunndevster** [comment]
@garyericson - Glad to hear!
