### ISSUE TITLE
Language metadata for VB snippets doesn't work with code picker

### ISSUE THREAD

**Issue by gewarren** [microsoft/vscode-docs-authoring#763]
I used the Docs Authoring Pack (Alt+M) to insert Visual Basic and C# snippets in my markdown file. A public contributor noticed that examples for both languages (C# and VB) displayed no matter which one was selected in the code selector. The fix was to replace `language="vbnet"` with `language="vb"`. See https://github.com/dotnet/docs/pull/20965/files for the change we had to make. The DAP should be updated to use `language="vb"` when inserting VB snippets.

[AB#318639](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/318639)

**Comment by meganbradley** [comment]
This is in scope for https://dev.azure.com/ceapex/Engineering/_workitems/edit/337817. Please track there.
