### ISSUE TITLE
xref displayProperty ignored in preview

### ISSUE THREAD

**Issue by rainersigwald** [microsoft/vscode-docs-authoring#776]
It looks like the `displayProperty` part of an `<xref:System.Byte?displayProperty=nameWithType>` is not being respected in preview.

For example:

![image](https://user-images.githubusercontent.com/3347530/99697850-b90a9f80-2a55-11eb-9e17-defca007f233.png)

but on the [live page](https://docs.microsoft.com/visualstudio/msbuild/property-functions?view=vs-2019#static-property-functions):

![image](https://user-images.githubusercontent.com/3347530/99697912-c9bb1580-2a55-11eb-88b3-4f1f05db737f.png)

[AB#338989](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/338989)

**Comment by adegeo** [comment]
Can someone triage and prioritize this bug?

**Comment by bharney0** [comment]
@rainersigwald @adegeo looking into this issue. Thank you for reporting the bug and sorry about not getting to this sooner.
