### ISSUE TITLE
Preview stops processing article if :::code is present.

### ISSUE THREAD

**Issue by adegeo** [microsoft/vscode-docs-authoring#802]
I have the docs authoring pack installed. If a `:::code` element is added to an article, it stops processing the preview and simply presents the previous preview of whatever article you last looked at that was successfully rendered.

I used this markdown specifically:

```
:::code language="xaml" source="snippets/create-app-visual-studio/csharp/MainWindow.xaml" highlight="8":::
```

**Comment by jamarw** [comment]
Hey @adegeo , created a bug for this. Thanks for reporting it.

AB#364731

**Comment by adegeo** [comment]
@jamarw has this ever supported rendering the code blocks from these snippets? I've never seen it work. Just the old style snippets.

**Comment by bharney0** [comment]
@adegeo we've had issues in the past where users are not seeing updated code snippet after changing the code snippet file but the code snippet `:::code:::` tags should render in preview as seen here:
![image](https://user-images.githubusercontent.com/51799435/107556084-d2227880-6b8c-11eb-9175-7b54807c8da6.png)

Do you have any more details with a repo and example that we can repro the issue? And what machine are you running on? Windows? Mac? Thanks again for reporting the issue, we hope to resolve your issue soon.

**Comment by adegeo** [comment]
@bharney0 Sorry for the delay, I was out.

It's very odd and inconsistent. I'm on Windows. 

--- Update

I just 10 minutes of testing and playing around and I think I've figured out the problem. If you have a `:::code` inside an XML comment in the document, the processing crashes and whatever was previously displayed in preview is carried forward, even if it was some other article. I'm constantly working in an area where I'm upgrading existing content so I mark things with XML comments to comment them out as I work and keep them out of way, sometimes even publishing them until other articles are ready.

To repo:

01. Close all VSCode instances
01. In a terminal, navigate to a new folder with no articles
01. Create an article with `code test.md` which opens VSCode
01. Paste in the following:

    ```markdown
    DELETE ME
    Snippet examples
    <!--
    :::code language="xaml" source="snippets/create-app-visual-studio/csharp/LayoutStep3.xaml" range="9-23" highlight="13":::
    :::code language="xaml" source="snippets/create-app-visual-studio/csharp/MoreControls2.xaml" id="StackPanel1":::
    :::code language="xaml" source="snippets/create-app-visual-studio/csharp/MoreControls3.xaml" id="ButtonEvent" highlight="3":::
    :::code language="csharp" source="snippets/create-app-visual-studio/csharp/MoreControls3.xaml.cs" id="ButtonEvent":::
    :::code language="vb" source="snippets/create-app-visual-studio/vb/MoreControls3.xaml.vb" id="ButtonEvent":::
    -->
    ```
01. Show the Docs: Preview and see that nothing is rendered

Here is a gif showing it with the preview already open. Notice how the processing stops as soon as this is present:

![problem](https://user-images.githubusercontent.com/67293991/108108188-245c1180-7045-11eb-89af-1394f915e4c9.gif)

**Comment by bharney0** [comment]
@adegeo Thank you for the detailed explanation of the issue. This helped me troubleshoot relatively easily and resolve the problem. I have a PR #814 open with the fix and we should get it merged this week.
