### ISSUE TITLE
url-encoded links

### ISSUE THREAD

**Issue by cristianmtr** [microsoft/vscode-docs-authoring#804]
Hello

I love this extension and I use it all the time. Thanks so much for making it!

I do wish however that when inserting a link to another file, it would automatically replace spaces (` `) in the filename with the url-encoded space character ( `%20`) to make sure it's clickable.

See screenshot

![image](https://user-images.githubusercontent.com/8330330/105835428-1548ed00-5fcc-11eb-93d2-f273155fc257.png)

**Comment by bharney0** [comment]
@cristianmtr great idea! Thank you for the feedback. I made a very minor PR to resolve the issue where there are files getting linked with spaces. This PR should get merged sometime later this week.
