### ISSUE TITLE
Toolbar configuration enhancement

### ISSUE THREAD

**Issue by scottaddie** [Microsoft/vscode-docs-authoring#82]
I prefer to use the legacy toolbar with the extension. I followed the instructions to enable the toolbar, and that worked great. The problem is that now I have 2 toolbars.

![image](https://user-images.githubusercontent.com/10702007/41985835-1331bfe8-79fa-11e8-8445-edb9a0ad0336.png)

The toolbar at the top ☝️ of the editor should disappear when I enable the legacy toolbar. That's valuable real estate at the top that should be consumed by tabs instead.

**Comment by jamarw** [comment]
HI @scottaddie , agreed and thanks for the feedback.  Working to resolve this now.

**Comment by jamarw** [comment]
Pull request awaiting review

**Comment by jamarw** [comment]
The latest release, 0.1.2, frees up space in the navigation window.  Thanks again and please let us know if you run into any issues or have suggestions.
