### ISSUE TITLE
The docs-markdown extension only works on Markdown files.

### ISSUE THREAD

**Issue by mlc-mlapis** [microsoft/vscode-docs-authoring#832]
With VS Code 1.53.2 the known problem with constant Warning Message When Editing Non-Markdown Files has been appearing again, for example when opening `package.json`.

Previously it was solved in https://github.com/microsoft/vscode-docs-authoring/issues/441.

![image](https://user-images.githubusercontent.com/5693835/109562141-4e4e1300-7ade-11eb-9efd-788cf3acdbb2.png)

**Comment by bharney0** [comment]
@mlc-mlapis can you make sure you are on the latest version of docs-markdown 0.2.84? We just released a fix for this today 03/01/2021, and then check if the problem still persists?

**Comment by mlc-mlapis** [comment]
@bharney0 Yep, you are right. With 0.2.84, the problem disappeared. Great. 👍
