### ISSUE TITLE
Cannot render normal checkbox like GitHub

### ISSUE THREAD

**Issue by Brian-Ding** [microsoft/vscode-docs-authoring#835]
Is it possible to render a checkbox just like the GitHub does here?

With markdown code as below
``` md
- [ ] Todo 1
- [x] Todo 2
```
I am expecting
> - [ ] Todo 1
> - [x] Todo 2

What I really get is
> \- \[ \] Todo 1
> \- \[x\] Todo 2

**Comment by bharney0** [comment]
@Brian-Ding unfortunately our markdown parser does not support GitHub flavor markdown but instead Docs markdown. We have the ability to do a checkbox, but its not necessarily like GitHub's checkbox. You can find our reference guide on what markdown syntax we support [here](https://docs.microsoft.com/en-us/contribute/markdown-reference#checklist). The checklist can be seen here:
![image](https://user-images.githubusercontent.com/51799435/110007985-1a3a4400-7cd0-11eb-8362-84c408ec2bb4.png)

Sorry again, and if this requirement continues to come up we may decide to support it in the future, but until then I would recommend using this type of syntax
```
> [!div class="checklist"]
> * Todo 1
> * Todo 2
```

**Comment by Brian-Ding** [comment]
I came across this syxtax on the docs website before I submitted the issue. the problem is how to make the  "to do item" not checked ?

**Comment by bharney0** [comment]
@meganbradley is it possible to render checklist with some items not checked? I dont think I've seen that before?

**Comment by meganbradley** [comment]
@bharney0 @Brian-Ding 
No, this isn't currently supported. If there's significant demand and no big barriers (like accessibility) we might consider it in the future, but it's not a priority at this time.

**Comment by bharney0** [comment]
@Brian-Ding you can do a work around that renders correctly from the docs rendering pipeline:
```
> [!div class="checklist"]
> * List item 1
> * List item 2
> <br/>List item 3
> * List item 4
```
![image](https://user-images.githubusercontent.com/51799435/110370380-6f43c600-8000-11eb-80a2-fdb67d4407f3.png)

However it does not render correctly in docs-preview in VSCode:
![image](https://user-images.githubusercontent.com/51799435/110370491-969a9300-8000-11eb-99fe-a63c808dab9c.png)

**Comment by Brian-Ding** [comment]
@bharney0 thx for the tip!

**Comment by bharney0** [comment]
Closing this issue due to the fact its not on the future plan to support checkboxlist without checked items. The work around can be found above but its somewhat hacky. If this is frequently requested in the future we can add support for it in the authoring pack and update the docs publishing pipeline.
