### ISSUE TITLE
Several templates disappeared from Docs: Template menu

### ISSUE THREAD

**Issue by SKjerland** [microsoft/vscode-docs-authoring#837]
My team has two article templates that are part of the **Docs: Template** menu. These are **smb-article-template.md** and **smb-faq-template.md**. These templates somehow dropped out of the menu. In fact, it looks like a bunch of the templates that used to be part of this menu have disappeared. I'm only seeing 6 there now. Can someone please look into this problem so we can get our templates back? Thanks!

**Comment by bharney0** [comment]
@jamarw can you check on this? I believe this has to do with the changes made to the docs article templates/scaffolding.

**Comment by jamarw** [comment]
Hi @SKjerland , an updated version of the template extension was released to support friendly names and repo-specific templates. I've contacted the PM team to let them know we need to get your templates added. Thanks and I'll check back in on this soon.

**Comment by meganbradley** [comment]
@SKjerland apologies! We restructured the template menu and lost a few. Can you let us know what repos you want them to show up in? We'll get them back ASAP.

**Comment by SKjerland** [comment]
@meganbradley - I thought the templates could be used from any repo as long as you have the Docs Article Templates Extension enabled in VS Code? I don't recall templates needing to be tied to specific repos previously. I know our main repo is **microsoft-365-docs-pr**, but there may be other repos that my co-workers work in that I don't know about. Also, we may be adding a new repo for some partner content and we would want to use the template there. Is there no way to make templates available across all repos?

**Comment by meganbradley** [comment]
@SKjerland I can make them available for all repos for now, but it would be better to have a list of repos where they're likely to be used. The list was getting very long and most templates aren't applicable to most repos, so we're trying to scope them appropriately to reduce noise. Do you have a team alias I could send a query to to try to get the right list?

**Comment by SKjerland** [comment]
@meganbradley - Okay, I understand. I asked our team and they said it's okay to scope them to **microsoft-365-docs-pr** for now. If we need to use them in other repos in the future, should I just email you? Or is there another process you want me to follow? Thanks!

**Comment by meganbradley** [comment]
Thanks @skjerland. I added the SMB templates to the microsoft-365-docs-pr repo and verified that they're showing up. Let me know if you want different friendly names. To get them added to other repos in the future, it's probably better to file an issue and @ mention me and Jamar, just so the request isn't delayed if I'm on vacation or something.

**Comment by SKjerland** [comment]
@meganbradley - I can see them now! Thanks! The friendly names are great. I will be sure to file and issue @mention you and Jamar if we need them added to other repos in the future. Thanks for fixing this so quickly!
