### ISSUE TITLE
Unescaped xref syntax regex needs to be updated

### ISSUE THREAD

**Issue by scottaddie** [microsoft/vscode-docs-authoring#842]
The [regex used for detecting unescaped xref syntax](https://github.com/microsoft/vscode-docs-authoring/blob/bd1be51df5a96daf4acdc0a99fb0cea25256248e/packages/docs-linting/markdownlint-custom-rules/common.js#L94) needs to be updated. It currently warns about unescaped `#` characters. For example, the following line would be flagged:

```md
[how to download](xref:index#how-to-download-a-sample)
```

Converting this line to the following resolves the warning in VS Code:

```md
[how to download](xref:index%23how-to-download-a-sample)
```

However, the encoding of the character with `%23` creates OPS build warnings. For example:

![image](https://user-images.githubusercontent.com/10702007/111176182-1a133180-8577-11eb-98e4-f516427065c6.png)

My proposal is to remove `#` from the aforementioned regex.

/cc: @guardrex

**Comment by nschonni** [comment]
I think the current regex is incorrect, but I'm wondering if it was more to catch a double `##` (that I vaguely remember used somewere), but isn't valid in URLs
