### ISSUE TITLE
Add lightbox to image selection does not work. Also, alt-text displays as caption.

### ISSUE THREAD

**Issue by roygara** [microsoft/vscode-docs-authoring#844]
Not sure why but, when I try to use the docs plugin to add a lightbox to an image, it will always fail, with the error that the cursor must be in the image tag. Regardless of where the cursor is in the image tag. The actual syntax works fine, if I write it in by hand, but the plugin is unable to detect that it is in an image tag and fails, when adding a lightbox. Also, I see that the alt-text is displaying as a caption again. Is this intentional behavior? (Mentioned the alt-text displaying as caption in previous issue https://github.com/microsoft/vscode-docs-authoring/issues/608)

Plugin cannot detect cursor in image tag:
![add-lightbox-to-image](https://user-images.githubusercontent.com/31490067/111236722-c9202f00-85b0-11eb-8bce-b0f701a1d8fa.png)

![lightbox-error](https://user-images.githubusercontent.com/31490067/111236729-cb828900-85b0-11eb-8e02-3d704d97de2c.png)

Alt-text as caption:
![alt-text-displayed-as-caption](https://user-images.githubusercontent.com/31490067/111236929-3c29a580-85b1-11eb-82fa-39108f3a53eb.png)

**Comment by bharney0** [comment]
@roygara thank you for reporting this issue I have a fix for the Docs Authoring Pack tooling for inserting lightbox attributes when having a cursor on the :::image::: tag. Please see this PR linked here #863. However regarding the lightbox rendering in the publishing pipeline that is a bigger issue that we should address and have a PM discuss what the functionality should be. I am assuming we should not display alt-text in the lightbox caption area. @meganbradley can we look more into this issue? Should the lightbox display alt-text as a caption when using the :::image::: tag where as the conventional md lightbox syntax doesnt do this? I created an AzureDevOps issue to track it AB#420622

**Comment by bharney0** [comment]
@roygara this fix should ship to production this week FYI

**Comment by roygara** [comment]
Thanks, @bharney0 , I appreciate it! :)
