### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by shortpatti** [microsoft/vscode-docs-authoring#849]
- Issue Type: `Performance`
- Extension Name: `docs-markdown`
- Extension Version: `0.2.85`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.54.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\v-patsho\AppData\Local\Temp\docsmsft.docs-markdown-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by shortpatti** [comment]
[docsmsft.docs-markdown-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-docs-authoring/files/6223328/docsmsft.docs-markdown-unresponsive.cpuprofile.txt)

**Comment by bharney0** [comment]
@shortpatti Can you give any more details about what you were doing in the extension that cuased the high CPU load? It tried to troubleshoot with the cpuprofiler but its difficult to say what the exact issue is.

**Comment by shortpatti** [comment]
@bharney0, I honestly can't remember what I was doing to cause this CPU load.  You can close this issue.
