### ISSUE TITLE
Enable links in toc.yml files

### ISSUE THREAD

**Issue by JimDaly** [Microsoft/vscode-docs-authoring#86]
The ability to set links in toc.yml would be a big help.
Rather than markdown links, it would insert the `name` and  `href` properties in the location of the cursor.

**Comment by jamarw** [comment]
Hi @JimDaly , thanks for the suggestion.  Looping in PM.

**Comment by meganbradley** [comment]
@JimDaly 
In the queue as VSTS #42146 - closing this issue.

**Comment by meganbradley** [comment]
This feature is live in the latest release of the Docs Authoring Pack.
