### ISSUE TITLE
Header link generator of tool not working

### ISSUE THREAD

**Issue by adegeo** [microsoft/vscode-docs-authoring#880]
Using the **Link to heading** feature of the extension is no longer working. It's displaying each letter of the header as in individual result. Multiple team members have confirmed this behavior in out Teams channel.

![image](https://user-images.githubusercontent.com/67293991/120392917-052c7b80-c2e6-11eb-9e52-72150d5c2bb5.png)

@tdykstra @IEvangelist

**Comment by IEvangelist** [comment]
I too am seeing this, I'm not sure - but it might be related to #875

**Comment by roygara** [comment]
Yeah I'm seeing this as well.

**Comment by jamarw** [comment]
Hi all, I'm looking into this now and should have a fix soon. Thanks for reporting this to us.

**Comment by jamarw** [comment]
https://github.com/microsoft/vscode-docs-authoring/pull/881
